SB-2020-2-JVM: InterfaceInfo Class Reference
InterfaceInfo Class Reference
#include <interface_info.hpp>
Public Member Functions
InterfaceInfo (ClassFile *class_file)
void printInfo ()
Private Attributes
uint16_t interface_info
ClassFile * class_file
Detailed Description
Definition at line 11 of file interface_info.hpp.
Constructor & Destructor Documentation
InterfaceInfo()
InterfaceInfo::InterfaceInfo (ClassFile * class_file)
Definition at line 3 of file interface_info.cpp.
{
     this->class_file = class_file;
     this->class_file->file_reader->readBytes(2, this->interface_info);
 }
References class_file, ClassFile::file_reader, interface_info, and FileReader::readBytes().
Member Function Documentation
printInfo()
void InterfaceInfo::printInfo ()
Definition at line 8 of file interface_info.cpp.
{
   cout << dec;
   cout << "\tIndex: \t cpinfo #" << this->interface_info << " " << this->class_file->getConstantPoolEntry(this->interface_info)->toString() << endl;
 }
References class_file, ClassFile::getConstantPoolEntry(), interface_info, and CpInfo::toString().
Field Documentation
class_file
ClassFile* InterfaceInfo::class_file private
Definition at line 14 of file interface_info.hpp.
Referenced by InterfaceInfo(), and printInfo().
interface_info
uint16_t InterfaceInfo::interface_info private
Definition at line 13 of file interface_info.hpp.
Referenced by InterfaceInfo(), and printInfo().
The documentation for this class was generated from the following files:
include/interface_info.hpp
src/interface_info.cpp