SB-2020-2-JVM: Instructions::InterfaceAstore Class Reference
Instructions::InterfaceAstore Class Reference
#include <_astore.hpp>
Public Member Functions
InterfaceAstore (Attribute::CodeAttribute *code_attr, uint8_t opcode)
virtual int execute (Frame *frame)
virtual JVMType getType ()
Public Member Functions inherited from Instructions::BaseInstruction
BaseInstruction (Attribute::CodeAttribute *code_attr, uint8_t opcode)
virtual ~BaseInstruction ()
virtual void print ()
virtual void print (int)
virtual string toString ()
Additional Inherited Members
Static Public Member Functions inherited from Instructions::BaseInstruction
static string getTypePrefix (uint8_t type)
static BaseInstruction * getInstance (Attribute::CodeAttribute *code_attr, uint8_t opcode, uint32_t pc)
Data Fields inherited from Instructions::BaseInstruction
uint8_t opcode
uint16_t pc
Protected Member Functions inherited from Instructions::BaseInstruction
string hexToString (int)
string intToString (int)
string intToSignedString (int)
string createStringWithCPRef (string name, uint16_t index)
string tabs (int)
Protected Attributes inherited from Instructions::BaseInstruction
Attribute::CodeAttribute * code_attr
Detailed Description
Definition at line 9 of file _astore.hpp.
Constructor & Destructor Documentation
InterfaceAstore()
InterfaceAstore::InterfaceAstore (Attribute::CodeAttribute * code_attr, uint8_t opcode)
Definition at line 5 of file _astore.cpp.
   :BaseInstruction(code_attr, opcode){}
Member Function Documentation
execute()
int InterfaceAstore::execute (Frame * frame) virtual
Reimplemented from Instructions::BaseInstruction.
Definition at line 9 of file _astore.cpp.
{
   uint64_t arrayref, index, value;
   value     = frame->operand_stack.pop().first;
   index     = frame->operand_stack.pop().first;
   arrayref  = frame->operand_stack.pop().first;
   ArrayType* array = (ArrayType*)frame->thread->heap_ref->getReference(arrayref);
   array->setIndexAsPrimitiveType(index, value, this->getType());
   return frame->local_pc++;
 }
References Heap::getReference(), getType(), Thread::heap_ref, Frame::local_pc, Frame::operand_stack, OperandStack::pop(), ArrayType::setIndexAsPrimitiveType(), and Frame::thread.
getType()
JVMType InterfaceAstore::getType () virtual
Reimplemented in Instructions::Sastore, Instructions::Castore, Instructions::Bastore, Instructions::Aastore, Instructions::Dastore, Instructions::Fastore, Instructions::Lastore, and Instructions::Iastore.
Definition at line 7 of file _astore.cpp.
 {return Reference;}
References Reference.
Referenced by execute().
The documentation for this class was generated from the following files:
include/attribute_info_classes/instruction_classes/_astore.hpp
src/attribute_info_classes/instruction_classes/_astore.cpp