SB-2020-2-JVM: JVMInterface Class Reference
JVMInterface Class Reference
#include <jvm_interface.hpp>
Public Member Functions
JVMInterface (string interface_name)
void setClassFile (ClassFile *)
void addField (JVMField *)
JVMField * getField (string field_name)
PrimitiveType getConstant (int index)
string toString ()
Public Member Functions inherited from ComponentType
ComponentType (JVMType component_type)
void setReference (int)
int getReference ()
virtual void print ()
virtual ~ComponentType ()
Data Fields
vector< pair< string, uint64_t > > constant_strings
Data Fields inherited from ComponentType
JVMType type
Private Attributes
string interface_name
vector< JVMField * > fields
ClassFile * class_file
Additional Inherited Members
Static Public Member Functions inherited from ComponentType
static ComponentType * getDefaultValue (JVMType)
static JVMType getTypeFromDescriptor (string descriptor)
Protected Attributes inherited from ComponentType
int heap_reference
Detailed Description
Definition at line 14 of file jvm_interface.hpp.
Constructor & Destructor Documentation
JVMInterface()
JVMInterface::JVMInterface (string interface_name)
Definition at line 9 of file jvm_interface.cpp.
                                                :ComponentType(JVMINTERFACE){
     this->interface_name = interface_name;
 }
References interface_name.
Member Function Documentation
addField()
void JVMInterface::addField (JVMField * a)
Definition at line 26 of file jvm_interface.cpp.
{
     this->fields.push_back(a);
 }
References fields.
Referenced by InterfaceLoader::linkInterface().
getConstant()
PrimitiveType JVMInterface::getConstant (int index)
Definition at line 17 of file jvm_interface.cpp.
{
     uint64_t return_data;
     JVMType return_type;
     return PrimitiveType(return_data, return_type);
 }
getField()
JVMField * JVMInterface::getField (string field_name)
Definition at line 30 of file jvm_interface.cpp.
{
     for(uint16_t i=0;i< this->fields.size();i++){
         if(this->fields[i]->field_name == field_name){
             return this->fields[i];
         }
     }
     throw std::runtime_error("ResolveFieldError: " + field_name + "not found");
 }
References fields.
setClassFile()
void JVMInterface::setClassFile (ClassFile * c)
Definition at line 13 of file jvm_interface.cpp.
{
     this->class_file = c;
 }
References class_file.
Referenced by InterfaceLoader::linkInterface().
toString()
string JVMInterface::toString () virtual
Reimplemented from ComponentType.
Definition at line 39 of file jvm_interface.cpp.
{
     stringstream paramString;
     paramString << "{ Interface: " << this->class_file->getThisClassName() << " ";
     paramString << "fields(" << this->fields.size() << "){";
     for(uint16_t i=0;i< this->fields.size();i++){
         paramString << this->fields[i]->toString();
         if(i!=  this->fields.size()-1){
             paramString << ", ";
         }
     }
     paramString << "}}";
     return paramString.str();
 }
References class_file, fields, and ClassFile::getThisClassName().
Field Documentation
class_file
ClassFile* JVMInterface::class_file private
Definition at line 18 of file jvm_interface.hpp.
Referenced by setClassFile(), and toString().
constant_strings
vector<pair<string, uint64_t> > JVMInterface::constant_strings
Definition at line 22 of file jvm_interface.hpp.
fields
vector<JVMField*> JVMInterface::fields private
Definition at line 17 of file jvm_interface.hpp.
Referenced by addField(), getField(), and toString().
interface_name
string JVMInterface::interface_name private
Definition at line 16 of file jvm_interface.hpp.
Referenced by JVMInterface().
The documentation for this class was generated from the following files:
include/interpretador/types/jvm_interface.hpp
src/interpretador/types/jvm_interface.cpp