SB-2020-2-JVM: JVMObject Class Reference
JVMObject Class Reference
#include <jvm_object.hpp>
Public Member Functions
JVMObject (string class_name)
void initializeFields ()
Public Member Functions inherited from JVMClass
JVMClass (string class_name)
void setClassFile (ClassFile *)
void addField (JVMField *)
JVMField * getField (string field_name)
PrimitiveType getConstant (int index)
virtual string toString ()
Public Member Functions inherited from ComponentType
ComponentType (JVMType component_type)
void setReference (int)
int getReference ()
virtual void print ()
virtual ~ComponentType ()
Additional Inherited Members
Static Public Member Functions inherited from JVMClass
static vector< JVMField * > getFieldsFor (string class_name)
Static Public Member Functions inherited from ComponentType
static ComponentType * getDefaultValue (JVMType)
static JVMType getTypeFromDescriptor (string descriptor)
Data Fields inherited from JVMClass
ClassFile * class_file
vector< pair< string, uint64_t > > constant_strings
Data Fields inherited from ComponentType
JVMType type
Protected Attributes inherited from JVMClass
string class_name
vector< JVMField * > fields
Protected Attributes inherited from ComponentType
int heap_reference
Detailed Description
Definition at line 8 of file jvm_object.hpp.
Constructor & Destructor Documentation
JVMObject()
JVMObject::JVMObject (string class_name)
Definition at line 5 of file jvm_object.cpp.
 :JVMClass(c){}
Member Function Documentation
initializeFields()
void JVMObject::initializeFields () virtual
Reimplemented from JVMClass.
Definition at line 7 of file jvm_object.cpp.
{
   vector<JVMField*> allFields = JVMClass::getFieldsFor(this->class_name);
   for(size_t i=0;i<allFields.size();i+=1){
     JVMField* field = allFields[i];
     if(!field->field_info_ref->isStatic()){
       this->addField(field);
     }
   }
 }
References JVMClass::addField(), JVMClass::class_name, JVMField::field_info_ref, JVMClass::getFieldsFor(), and FieldInfo::isStatic().
Referenced by Instructions::New::execute(), and ReferenceResolver::resolveObjectByDescriptor().
The documentation for this class was generated from the following files:
include/interpretador/types/jvm_object.hpp
src/interpretador/types/jvm_object.cpp