SB-2020-2-JVM: Instructions::MultiANewArray Class Reference
Instructions::MultiANewArray Class Reference
#include <multianewarray.hpp>
Public Member Functions
MultiANewArray (Attribute::CodeAttribute *code_attr, uint8_t opcode)
string toString ()
int execute (Frame *frame)
Public Member Functions inherited from Instructions::BaseInstruction
BaseInstruction (Attribute::CodeAttribute *code_attr, uint8_t opcode)
virtual ~BaseInstruction ()
virtual void print ()
virtual void print (int)
Data Fields
uint8_t dimensions
uint16_t index
Data Fields inherited from Instructions::BaseInstruction
uint8_t opcode
uint16_t pc
Additional Inherited Members
Static Public Member Functions inherited from Instructions::BaseInstruction
static string getTypePrefix (uint8_t type)
static BaseInstruction * getInstance (Attribute::CodeAttribute *code_attr, uint8_t opcode, uint32_t pc)
Protected Member Functions inherited from Instructions::BaseInstruction
string hexToString (int)
string intToString (int)
string intToSignedString (int)
string createStringWithCPRef (string name, uint16_t index)
string tabs (int)
Protected Attributes inherited from Instructions::BaseInstruction
Attribute::CodeAttribute * code_attr
Detailed Description
Definition at line 8 of file multianewarray.hpp.
Constructor & Destructor Documentation
MultiANewArray()
MultiANewArray::MultiANewArray (Attribute::CodeAttribute * code_attr, uint8_t opcode)
Definition at line 9 of file multianewarray.cpp.
     :BaseInstruction(code_attr, opcode){
   FileReader *f = this->code_attr->class_file->file_reader;
   f->readBytes(2, this->index);
   f->readBytes(1, this->dimensions);
 }
References AttributeInfo::class_file, dimensions, ClassFile::file_reader, index, and FileReader::readBytes().
Member Function Documentation
execute()
int MultiANewArray::execute (Frame * frame) virtual
Reimplemented from Instructions::BaseInstruction.
Definition at line 21 of file multianewarray.cpp.
{
     vector<uint64_t> dims;
     for(size_t i=0; i<this->dimensions;i+=1){
       dims.push_back(frame->operand_stack.pop().first);
     }
     reverse(dims.begin(), dims.end());
     // Todo: verificar dimensoes invalidas
     CpInfo* cp_entry = this->code_attr->class_file->getConstantPoolEntry(this->index);
     int heap_ref = ReferenceResolver::allocateArray(cp_entry->toString(), frame->thread->method_area, dims);
     frame->operand_stack.push(heap_ref, Reference);
     return frame->local_pc+=4;
 }
References ReferenceResolver::allocateArray(), AttributeInfo::class_file, Instructions::BaseInstruction::code_attr, dimensions, ClassFile::getConstantPoolEntry(), index, Frame::local_pc, Thread::method_area, Frame::operand_stack, OperandStack::pop(), OperandStack::push(), Reference, Frame::thread, and CpInfo::toString().
toString()
string MultiANewArray::toString () virtual
Reimplemented from Instructions::BaseInstruction.
Definition at line 16 of file multianewarray.cpp.
{
   return this->createStringWithCPRef("multianewarray", this->index) +
   " dimensions: " + this->intToString(this->dimensions);
 }
References Instructions::BaseInstruction::createStringWithCPRef(), dimensions, index, and Instructions::BaseInstruction::intToString().
Field Documentation
dimensions
uint8_t Instructions::MultiANewArray::dimensions
Definition at line 10 of file multianewarray.hpp.
Referenced by execute(), MultiANewArray(), and toString().
index
uint16_t Instructions::MultiANewArray::index
Definition at line 11 of file multianewarray.hpp.
Referenced by execute(), MultiANewArray(), and toString().
The documentation for this class was generated from the following files:
include/attribute_info_classes/instruction_classes/multianewarray.hpp
src/attribute_info_classes/instruction_classes/multianewarray.cpp