SB-2020-2-JVM: Thread Class Reference
Thread Class Reference
#include <thread.hpp>
Public Member Functions
Thread (MethodArea *)
void invokeStaticMethod (string class_name, string methodName, string args_descriptor)
void invokeInstanceMethod (string class_name, string methodName, string args_descriptor)
void popFrame ()
Frame * getCurrentFrame ()
void runMain ()
void start ()
void handleException (Frame *frame, int index)
Data Fields
MethodArea * method_area
Heap * heap_ref
Private Member Functions
void initializeFrameVariableVector (Frame *, int n_args, int initial_pos)
Private Attributes
uint32_t pc_register
MethodInfo * current_method
vector< Frame * > frame_stack
Detailed Description
Definition at line 13 of file thread.hpp.
Constructor & Destructor Documentation
Thread()
Thread::Thread (MethodArea * method_area)
Definition at line 6 of file thread.cpp.
{
   this->method_area = method_area;
   this->heap_ref = Heap::getInstance();
 }
References Heap::getInstance(), heap_ref, and method_area.
Member Function Documentation
getCurrentFrame()
Frame * Thread::getCurrentFrame ()
Definition at line 113 of file thread.cpp.
{
   return this->frame_stack.back();
 }
References frame_stack.
Referenced by Instructions::_Return::execute().
handleException()
void Thread::handleException (Frame * frame, int index)
Definition at line 45 of file thread.cpp.
{
   CP::ClassInfo *exception_name= (CP::ClassInfo *)frame->current_method->class_file->getConstantPoolEntry(index);
   ExceptionType* e = new ExceptionType(exception_name->toString());
   int heap_ref = Heap::getInstance()->storeComponent(e);
   frame->operand_stack.push(heap_ref, Reference);
 }
References MethodInfo::class_file, Frame::current_method, ClassFile::getConstantPoolEntry(), Heap::getInstance(), heap_ref, Frame::operand_stack, OperandStack::push(), Reference, Heap::storeComponent(), and CP::ClassInfo::toString().
Referenced by start().
initializeFrameVariableVector()
void Thread::initializeFrameVariableVector (Frame * f, int n_args, int initial_pos) private
Definition at line 53 of file thread.cpp.
{
   Frame* previous_frame = NULL;
   if(this->frame_stack.size() > 0)
     previous_frame = this->frame_stack.back();
   else if(n_args > 0) throw std::runtime_error("InvokeMethodError: invocando metodo com argumentos inexistentes no programa");
   vector<pair<uint64_t, JVMType>> args;
   for(int i=0;i<n_args;i+=1){
     pair<uint64_t, JVMType> arg = previous_frame->operand_stack.pop();
     args.push_back(arg);
   }
   reverse(args.begin(), args.end());
   int desloc = 0;
   int insertPosition = initial_pos;
   for(int i=0 ; i<n_args; i++ ){
     // TODO: Conferir tipagem na passagem de argumento
     pair<uint64_t, JVMType> arg = args[i];
     insertPosition = i + initial_pos + desloc;
     f->local_variables.insert(insertPosition + desloc, arg.first, arg.second);
     if(arg.second == Long || arg.second == Double)desloc++;
   }
 }
References Double, frame_stack, LocalVariable::insert(), Frame::local_variables, Long, Frame::operand_stack, and OperandStack::pop().
Referenced by invokeInstanceMethod(), and invokeStaticMethod().
invokeInstanceMethod()
void Thread::invokeInstanceMethod (string class_name, string methodName, string args_descriptor)
Definition at line 92 of file thread.cpp.
{
   MethodInfo* method = this->method_area->getMethodByName(class_name, methodName, args_descriptor);
   int n_args = method->getArgsCount();
   Frame* new_frame = new Frame(method, this);
   if(VERBOSE_INSTRUCTION_INVOKE){
     cout << "invokeInstanceMethod: Invocando metodo:" << methodName << " classname: " << class_name;
     cout << " argscount: " << n_args << endl;
   }
   this->initializeFrameVariableVector(new_frame, n_args+1, 0);
   this->frame_stack.push_back(new_frame);
 }
References frame_stack, MethodInfo::getArgsCount(), MethodArea::getMethodByName(), initializeFrameVariableVector(), method_area, and VERBOSE_INSTRUCTION_INVOKE.
Referenced by Instructions::InvokeVirtual::execute(), and Instructions::InvokeSpecial::execute().
invokeStaticMethod()
void Thread::invokeStaticMethod (string class_name, string methodName, string args_descriptor)
Definition at line 79 of file thread.cpp.
{
   MethodInfo* method = this->method_area->getMethodByName(class_name, methodName, args_descriptor);
   int n_args = method->getArgsCount();
   Frame* new_frame = new Frame(method, this);
   if(VERBOSE_INSTRUCTION_INVOKE){
     cout << "invokeStaticMethod: Invocando metodo:" << methodName << " n_agrs: " << endl;
   }
   this->initializeFrameVariableVector(new_frame, n_args, 0);
   this->frame_stack.push_back(new_frame);
 }
References frame_stack, MethodInfo::getArgsCount(), MethodArea::getMethodByName(), initializeFrameVariableVector(), method_area, and VERBOSE_INSTRUCTION_INVOKE.
Referenced by Instructions::InvokeStatic::execute(), and ClassLoader::initializeClass().
popFrame()
void Thread::popFrame ()
Definition at line 107 of file thread.cpp.
                      {
   Frame* current_frame = this->frame_stack.back();
   this->frame_stack.pop_back();
   delete current_frame;
 }
References frame_stack.
Referenced by Instructions::Return::execute(), and Instructions::_Return::execute().
runMain()
void Thread::runMain ()
Definition at line 11 of file thread.cpp.
                     {
   MethodInfo* current_method = this->method_area->getMainMethod();
   Frame* initial_frame = new Frame(current_method, this);
   this->frame_stack.push_back(initial_frame);
   this->start();
 }
References current_method, frame_stack, MethodArea::getMainMethod(), method_area, and start().
Referenced by ExecutionEngine::start().
start()
void Thread::start ()
Definition at line 20 of file thread.cpp.
                   {
   while(this->frame_stack.size() != 0){
     Frame* current_frame = this->frame_stack.back();
     if(VERBOSE_INSTRUCTION_PC){
       cout << "(" << current_frame->current_method->getName() << ")";
       cout << "Executando inst: " << current_frame->local_pc << endl;
     }
     try {
       current_frame->runInstruction();
     }
     catch (std::runtime_error e) {
         Attribute::CodeAttribute* code = current_frame->current_method->getCode();
         pair<int,int> handler = code->checkExceptionsTableForHandlers(current_frame->local_pc);
         if (handler.first >= 0) {
           current_frame->local_pc = handler.first;
           handleException(current_frame, handler.second);
         }
         else
           throw e;
     }
   }
 }
References Attribute::CodeAttribute::checkExceptionsTableForHandlers(), Frame::current_method, frame_stack, MethodInfo::getCode(), MethodInfo::getName(), handleException(), Frame::local_pc, Frame::runInstruction(), and VERBOSE_INSTRUCTION_PC.
Referenced by ClassLoader::initializeClass(), and runMain().
Field Documentation
current_method
MethodInfo* Thread::current_method private
Definition at line 17 of file thread.hpp.
Referenced by runMain().
frame_stack
vector<Frame*> Thread::frame_stack private
Definition at line 18 of file thread.hpp.
Referenced by getCurrentFrame(), initializeFrameVariableVector(), invokeInstanceMethod(), invokeStaticMethod(), popFrame(), runMain(), and start().
heap_ref
Heap* Thread::heap_ref
Definition at line 24 of file thread.hpp.
Referenced by Instructions::InterfaceAload::execute(), Instructions::InterfaceAstore::execute(), Instructions::Ldc::execute(), Instructions::LdcW::execute(), Instructions::NewArray::execute(), handleException(), and Thread().
method_area
MethodArea* Thread::method_area
Definition at line 23 of file thread.hpp.
Referenced by Instructions::New::execute(), Instructions::ANewArray::execute(), Instructions::GetStatic::execute(), Instructions::Ldc::execute(), Instructions::MultiANewArray::execute(), Instructions::PutStatic::execute(), invokeInstanceMethod(), invokeStaticMethod(), runMain(), and Thread().
pc_register
uint32_t Thread::pc_register private
Definition at line 15 of file thread.hpp.
The documentation for this class was generated from the following files:
include/interpretador/thread.hpp
src/interpretador/thread.cpp