SB-2020-2-JVM: Attribute::CodeAttribute Class Reference
Attribute::CodeAttribute Class Reference
#include <code_attribute.hpp>
Public Member Functions
CodeAttribute (AttrInitialValue initial_value)
~CodeAttribute ()
Instructions::BaseInstruction * getInstructionByPc (int pc)
pair< int, int > checkExceptionsTableForHandlers (int pc)
void printInfo (int n_tabs)
Public Member Functions inherited from AttributeInfo
AttributeInfo (Attribute::AttrInitialValue initial)
virtual ~AttributeInfo ()
string getAttributeName ()
Data Fields
uint16_t max_locals
uint32_t code_length
uint16_t number_of_instructions
Data Fields inherited from AttributeInfo
ClassFile * class_file
Private Member Functions
void loadInstructions ()
void loadExceptioTable ()
Private Attributes
uint16_t max_stack
vector< Instructions::BaseInstruction * > code
uint16_t exception_table_length
vector< CodeException * > exception_table
uint16_t attributes_count
vector< AttributeInfo * > attributes
Additional Inherited Members
Static Public Member Functions inherited from AttributeInfo
static AttributeInfo * getInstance (ClassFile *class_file)
static string createTabs (int n_tabs)
static void loadAttributes (vector< AttributeInfo * > &attributes, uint16_t size, ClassFile *class_file)
static void printAttributes (vector< AttributeInfo * > attributes, int n_tabs)
Protected Attributes inherited from AttributeInfo
uint16_t attribute_name_index
uint32_t attribute_length
Detailed Description
Definition at line 13 of file code_attribute.hpp.
Constructor & Destructor Documentation
CodeAttribute()
Attribute::CodeAttribute::CodeAttribute (AttrInitialValue initial_value)
Definition at line 3 of file code_attribute.cpp.
     :AttributeInfo(initial_value)
   {
     FileReader* file_reader = this->class_file->file_reader;
     this->number_of_instructions=0;
     file_reader->readBytes(2, this->max_stack);
     file_reader->readBytes(2, this->max_locals);
     file_reader->readBytes(4, this->code_length);
     this->loadInstructions();
     file_reader->readBytes(2, this->exception_table_length);
     this->loadExceptioTable();
     file_reader->readBytes(2, this->attributes_count);
     AttributeInfo::loadAttributes(this->attributes, this->attributes_count, this->class_file);
 }
References attributes, attributes_count, AttributeInfo::class_file, code_length, exception_table_length, ClassFile::file_reader, AttributeInfo::loadAttributes(), loadExceptioTable(), loadInstructions(), max_locals, max_stack, number_of_instructions, and FileReader::readBytes().
~CodeAttribute()
Attribute::CodeAttribute::~CodeAttribute ()
Definition at line 20 of file code_attribute.cpp.
{
   this->class_file->deleteVector<AttributeInfo*>(this->attributes);
   this->class_file->deleteVector<CodeException*>(this->exception_table);
   this->class_file->deleteVector(this->code);
 }
Member Function Documentation
checkExceptionsTableForHandlers()
pair< int, int > Attribute::CodeAttribute::checkExceptionsTableForHandlers (int pc)
Definition at line 74 of file code_attribute.cpp.
{
   pair<int, int> handler(-1,-1);
   for(int i=0; i<this->exception_table_length; i++) {
     handler = this->exception_table[i]->isPcHandled(pc);
     if (handler.first >= 0)
       return handler;
     else
       continue;
   }
   return handler;
 }
Referenced by Thread::start().
getInstructionByPc()
Instructions::BaseInstruction * Attribute::CodeAttribute::getInstructionByPc (int pc)
Definition at line 65 of file code_attribute.cpp.
{
   for(uint32_t i=0;i<this->code.size();i++){
     if((int)this->code[i]->pc == pc){
       return this->code[i];
     }
   }
   throw runtime_error("Opcode nao encontrado no codigo");
 }
Referenced by MethodInfo::getInstruction().
loadExceptioTable()
void Attribute::CodeAttribute::loadExceptioTable () private
Definition at line 46 of file code_attribute.cpp.
{
   for(uint16_t i=0;i<this->exception_table_length;i+=1){
     CodeException* newException = new CodeException(this);
     this->exception_table.push_back(newException);
   }
 }
Referenced by CodeAttribute().
loadInstructions()
void Attribute::CodeAttribute::loadInstructions () private
Definition at line 26 of file code_attribute.cpp.
{
   FileReader* file_reader = this->class_file->file_reader;
   int initial_pos, final_pos;
   for(uint16_t i=0;i<this->code_length;){
     uint8_t bytecode_read;
     initial_pos = file_reader->position;
     file_reader->readBytes(1, bytecode_read);
     Instructions::BaseInstruction* newInstruction = Instructions::BaseInstruction::getInstance(this, bytecode_read, i);
     newInstruction->pc = i;
     final_pos = file_reader->position;
     i += final_pos - initial_pos;
     this->code.push_back(newInstruction);
     this->number_of_instructions+=1;
   }
 }
References Instructions::BaseInstruction::getInstance(), Instructions::BaseInstruction::pc, FileReader::position, and FileReader::readBytes().
Referenced by CodeAttribute().
printInfo()
void Attribute::CodeAttribute::printInfo (int n_tabs) virtual
Reimplemented from AttributeInfo.
Definition at line 53 of file code_attribute.cpp.
{
   Instructions::BaseInstruction* newInstruction;
   AttributeInfo::printInfo(n_tabs);
   cout << createTabs(n_tabs+1) << "ByteCode: " << endl;
   for(int i=0; i < this->number_of_instructions;i+=1){
     newInstruction = this->code[i];
     cout << createTabs(n_tabs+2) << dec <<newInstruction->pc << "\t";
     newInstruction->print(n_tabs+2);
   }
 }
References Instructions::BaseInstruction::pc, Instructions::BaseInstruction::print(), and AttributeInfo::printInfo().
Field Documentation
attributes
vector<AttributeInfo*> Attribute::CodeAttribute::attributes private
Definition at line 22 of file code_attribute.hpp.
Referenced by CodeAttribute().
attributes_count
uint16_t Attribute::CodeAttribute::attributes_count private
Definition at line 21 of file code_attribute.hpp.
Referenced by CodeAttribute().
code
vector<Instructions::BaseInstruction*> Attribute::CodeAttribute::code private
Definition at line 16 of file code_attribute.hpp.
code_length
uint32_t Attribute::CodeAttribute::code_length
Definition at line 28 of file code_attribute.hpp.
Referenced by CodeAttribute().
exception_table
vector<CodeException*> Attribute::CodeAttribute::exception_table private
Definition at line 19 of file code_attribute.hpp.
exception_table_length
uint16_t Attribute::CodeAttribute::exception_table_length private
Definition at line 18 of file code_attribute.hpp.
Referenced by CodeAttribute().
max_locals
uint16_t Attribute::CodeAttribute::max_locals
Definition at line 27 of file code_attribute.hpp.
Referenced by CodeAttribute(), and Frame::Frame().
max_stack
uint16_t Attribute::CodeAttribute::max_stack private
Definition at line 15 of file code_attribute.hpp.
Referenced by CodeAttribute().
number_of_instructions
uint16_t Attribute::CodeAttribute::number_of_instructions
Definition at line 37 of file code_attribute.hpp.
Referenced by CodeAttribute().
The documentation for this class was generated from the following files:
include/attribute_info_classes/code_attribute.hpp
src/attribute_info_classes/code_attribute.cpp