SB-2020-2-JVM: Instructions::Ldc2W Class Reference
Instructions::Ldc2W Class Reference
#include <ldc.hpp>
Public Member Functions
Ldc2W (Attribute::CodeAttribute *code_attr, uint8_t opcode)
int execute (Frame *frame)
string toString ()
Public Member Functions inherited from Instructions::BaseInstruction
BaseInstruction (Attribute::CodeAttribute *code_attr, uint8_t opcode)
virtual ~BaseInstruction ()
virtual void print ()
virtual void print (int)
Private Attributes
uint16_t param
Additional Inherited Members
Static Public Member Functions inherited from Instructions::BaseInstruction
static string getTypePrefix (uint8_t type)
static BaseInstruction * getInstance (Attribute::CodeAttribute *code_attr, uint8_t opcode, uint32_t pc)
Data Fields inherited from Instructions::BaseInstruction
uint8_t opcode
uint16_t pc
Protected Member Functions inherited from Instructions::BaseInstruction
string hexToString (int)
string intToString (int)
string intToSignedString (int)
string createStringWithCPRef (string name, uint16_t index)
string tabs (int)
Protected Attributes inherited from Instructions::BaseInstruction
Attribute::CodeAttribute * code_attr
Detailed Description
Definition at line 26 of file ldc.hpp.
Constructor & Destructor Documentation
Ldc2W()
Ldc2W::Ldc2W (Attribute::CodeAttribute * code_attr, uint8_t opcode)
Definition at line 154 of file ldc.cpp.
     :BaseInstruction(code_attr, opcode){
   FileReader *f_reader = this->code_attr->class_file->file_reader;
   f_reader->readBytes(2, this->param);
 }
References AttributeInfo::class_file, ClassFile::file_reader, param, and FileReader::readBytes().
Member Function Documentation
execute()
int Ldc2W::execute (Frame * frame) virtual
Reimplemented from Instructions::BaseInstruction.
Definition at line 119 of file ldc.cpp.
{
     CpInfo* cp_entry = this->code_attr->class_file->getConstantPoolEntry(this->param);
     switch (cp_entry->tag) {
         case 0x5:{
             CP::LongInfo* cp_long = (CP::LongInfo *)cp_entry;
             frame->operand_stack.push(cp_long->returnLong(), Long);
             break;
         }
         case 0x6:{
             CP::DoubleInfo* cp_double = (CP::DoubleInfo *)cp_entry;
             double val = cp_double->returnDouble();
             frame->operand_stack.push(*(uint64_t*)&val, Double);
             break;
         }
         default:{
             throw std::runtime_error("wrong LDC2W cpinfo tag");
         }
     }
     return frame->local_pc+=3;
 }
References AttributeInfo::class_file, Instructions::BaseInstruction::code_attr, Double, ClassFile::getConstantPoolEntry(), Frame::local_pc, Long, Frame::operand_stack, param, OperandStack::push(), CP::DoubleInfo::returnDouble(), CP::LongInfo::returnLong(), and CpInfo::tag.
toString()
string Ldc2W::toString () virtual
Reimplemented from Instructions::BaseInstruction.
Definition at line 160 of file ldc.cpp.
                       {
   CpInfo* cp_val = this->code_attr->class_file->getConstantPoolEntry(this->param);
   stringstream paramString;
   paramString << (int)this->param;
   return "ldc2_w #" + paramString.str() + " <" + cp_val->toString() + ">";
 }
References AttributeInfo::class_file, Instructions::BaseInstruction::code_attr, ClassFile::getConstantPoolEntry(), param, and CpInfo::toString().
Field Documentation
param
uint16_t Instructions::Ldc2W::param private
Definition at line 28 of file ldc.hpp.
Referenced by execute(), Ldc2W(), and toString().
The documentation for this class was generated from the following files:
include/attribute_info_classes/instruction_classes/ldc.hpp
src/attribute_info_classes/instruction_classes/ldc.cpp