SB-2020-2-JVM: JVMClass Class Reference
JVMClass Class Reference
#include <jvm_class.hpp>
Public Member Functions
JVMClass (string class_name)
void setClassFile (ClassFile *)
void addField (JVMField *)
JVMField * getField (string field_name)
PrimitiveType getConstant (int index)
virtual void initializeFields ()
virtual string toString ()
Public Member Functions inherited from ComponentType
ComponentType (JVMType component_type)
void setReference (int)
int getReference ()
virtual void print ()
virtual ~ComponentType ()
Static Public Member Functions
static vector< JVMField * > getFieldsFor (string class_name)
Static Public Member Functions inherited from ComponentType
static ComponentType * getDefaultValue (JVMType)
static JVMType getTypeFromDescriptor (string descriptor)
Data Fields
ClassFile * class_file
vector< pair< string, uint64_t > > constant_strings
Data Fields inherited from ComponentType
JVMType type
Protected Attributes
string class_name
vector< JVMField * > fields
Protected Attributes inherited from ComponentType
int heap_reference
Detailed Description
Definition at line 14 of file jvm_class.hpp.
Constructor & Destructor Documentation
JVMClass()
JVMClass::JVMClass (string class_name)
Definition at line 7 of file jvm_class.cpp.
                                    :ComponentType(JVMCLASS){
   this->class_name = class_name;
   MethodArea* method_area = MethodArea::getInstance();
   this->class_file  = method_area->getClassFile(this->class_name);
 }
References class_file, class_name, MethodArea::getClassFile(), and MethodArea::getInstance().
Member Function Documentation
addField()
void JVMClass::addField (JVMField * a)
Definition at line 26 of file jvm_class.cpp.
{
   this->fields.push_back(a);
 }
References fields.
Referenced by initializeFields(), and JVMObject::initializeFields().
getConstant()
PrimitiveType JVMClass::getConstant (int index)
Definition at line 17 of file jvm_class.cpp.
{
   CpInfo* constant = this->class_file->getConstantPoolEntry(index);
   uint64_t return_data;
   JVMType return_type;
   return PrimitiveType(return_data, return_type);
 }
References class_file, and ClassFile::getConstantPoolEntry().
getField()
JVMField * JVMClass::getField (string field_name)
Definition at line 30 of file jvm_class.cpp.
{
   for(uint16_t i=0;i< this->fields.size();i++){
     if(this->fields[i]->field_name == field_name){
       return this->fields[i];
     }
   }
   throw std::runtime_error("ResolveFieldError: " + field_name + "not found");
 }
References fields.
Referenced by Instructions::GetField::execute(), Instructions::PutField::execute(), and ReferenceResolver::resolveStaticFieldSymbolicReference().
getFieldsFor()
vector< JVMField * > JVMClass::getFieldsFor (string class_name) static
Definition at line 69 of file jvm_class.cpp.
{
   vector<JVMField*> allFields;
   Heap* heap          = Heap::getInstance();
   MethodArea* m_a = MethodArea::getInstance();
   ClassFile* cl_file = m_a->getClassFile(class_name);
   for(uint16_t i=0;i< cl_file->fields.size();i+=1){
     FieldInfo* field  = cl_file->fields[i];
     JVMField* newFieldAlocated = new JVMField(field);
     heap->storeComponent(newFieldAlocated);
     allFields.push_back(newFieldAlocated);
   }
   if(cl_file->getSuperClassName() != "java/lang/Object"){
     vector<JVMField*> superFields = JVMClass::getFieldsFor(cl_file->getSuperClassName());
     allFields.insert(allFields.end(), superFields.begin(), superFields.end());
   }
   return allFields;
 }
References class_name, ClassFile::fields, MethodArea::getClassFile(), Heap::getInstance(), MethodArea::getInstance(), ClassFile::getSuperClassName(), and Heap::storeComponent().
Referenced by JVMObject::initializeFields().
initializeFields()
void JVMClass::initializeFields () virtual
Reimplemented in JVMObject.
Definition at line 39 of file jvm_class.cpp.
{
   Heap* heap          = Heap::getInstance();
   ClassFile* cl_file  = this->class_file;
   for(uint16_t i=0;i< cl_file->fields.size();i+=1){
     FieldInfo* field  = cl_file->fields[i];
     if(field->isStatic()){
       JVMField* newFieldAlocated = new JVMField(field);
       heap->storeComponent(newFieldAlocated);
       this->addField(newFieldAlocated);
     }
   }
 }
References addField(), class_file, ClassFile::fields, Heap::getInstance(), FieldInfo::isStatic(), and Heap::storeComponent().
Referenced by ClassLoader::linkClass().
setClassFile()
void JVMClass::setClassFile (ClassFile * c)
Definition at line 13 of file jvm_class.cpp.
{
   this->class_file = c;
 }
References class_file.
toString()
string JVMClass::toString () virtual
Reimplemented from ComponentType.
Definition at line 54 of file jvm_class.cpp.
{
   stringstream paramString;
   paramString << "{ Class: " << this->class_file->getThisClassName() << " ";
   paramString << "fields(" << this->fields.size() << "){";
   for(uint16_t i=0;i< this->fields.size();i++){
     paramString << this->fields[i]->toString();
     if(i!=  this->fields.size()-1){
       paramString << ", ";
     }
   }
   paramString << "}}";
   return paramString.str();
 }
References class_file, fields, and ClassFile::getThisClassName().
Field Documentation
class_file
ClassFile* JVMClass::class_file
Definition at line 21 of file jvm_class.hpp.
Referenced by getConstant(), initializeFields(), JVMClass(), ClassLoader::linkClass(), setClassFile(), and toString().
class_name
string JVMClass::class_name protected
Definition at line 16 of file jvm_class.hpp.
Referenced by getFieldsFor(), JVMObject::initializeFields(), and JVMClass().
constant_strings
vector<pair<string, uint64_t> > JVMClass::constant_strings
Definition at line 24 of file jvm_class.hpp.
fields
vector<JVMField*> JVMClass::fields protected
Definition at line 17 of file jvm_class.hpp.
Referenced by addField(), getField(), and toString().
The documentation for this class was generated from the following files:
include/interpretador/types/jvm_class.hpp
src/interpretador/types/jvm_class.cpp