SB-2020-2-JVM: ReferenceResolver Class Reference
ReferenceResolver Class Reference
#include <reference_resolver.hpp>
Static Public Member Functions
static pair< string, string > separateSymbol (string str, string delimiter)
static int resolveClassName (string class_name, MethodArea *)
static int resolveInterfaceName (string class_name, MethodArea *)
static JVMField * resolveStaticFieldSymbolicReference (string symbolic_reference, MethodArea *)
static int allocateArray (string descriptor, MethodArea *m_a, vector< uint64_t > dims)
static int resolveStringReference (string toResolve)
static bool isValidClassName (string class_name)
Static Private Member Functions
static int resolveObjectByDescriptor (string descriptor, MethodArea *m_a)
Detailed Description
Definition at line 13 of file reference_resolver.hpp.
Member Function Documentation
allocateArray()
int ReferenceResolver::allocateArray (string descriptor, MethodArea * m_a, vector< uint64_t > dims) static
Definition at line 68 of file reference_resolver.cpp.
{
   if(descriptor[0] == '['){
     descriptor.erase(0, 1);
     JVMType array_type = ComponentType::getTypeFromDescriptor(descriptor);
     ArrayType* newarray = new ArrayType(array_type);
     uint64_t array_length = dims[0];
     dims.erase(dims.begin());
     for(size_t i=0;i<array_length;i+=1){
       if(descriptor[0] == '[' || descriptor[0] == 'L'){
         int ref = ReferenceResolver::allocateArray(descriptor, m_a, dims);
         PrimitiveType* new_el = new PrimitiveType(ref, Reference);
         newarray->insert(new_el);
       }
       else{
         ComponentType* newprimitive = ComponentType::getDefaultValue(array_type);
         newarray->insert(newprimitive);
       }
     }
     return Heap::getInstance()->storeComponent(newarray);;
   }
   else{
     return ReferenceResolver::resolveObjectByDescriptor(descriptor, m_a);
   }
 }
References ComponentType::getDefaultValue(), Heap::getInstance(), ComponentType::getTypeFromDescriptor(), ArrayType::insert(), Reference, resolveObjectByDescriptor(), and Heap::storeComponent().
Referenced by Instructions::ANewArray::execute(), and Instructions::MultiANewArray::execute().
isValidClassName()
bool ReferenceResolver::isValidClassName (string class_name) static
Definition at line 99 of file reference_resolver.cpp.
{
   return (
     class_name.find("java/lang") == std::string::npos
   );
 }
Referenced by Instructions::GetStatic::execute(), Instructions::InvokeSpecial::execute(), and resolveClassName().
resolveClassName()
int ReferenceResolver::resolveClassName (string class_name, MethodArea * m_a) static
Definition at line 37 of file reference_resolver.cpp.
{
   if(ReferenceResolver::isValidClassName(class_name)){
     return ClassLoader::resolveClass(class_name, m_a);
   }
   else return -1;
 }
References isValidClassName(), and ClassLoader::resolveClass().
Referenced by Instructions::New::execute(), Instructions::Ldc::execute(), and resolveObjectByDescriptor().
resolveInterfaceName()
int ReferenceResolver::resolveInterfaceName (string class_name, MethodArea * m_a) static
Definition at line 95 of file reference_resolver.cpp.
{
     return InterfaceLoader::resolveInterface(interface_name, m_a);
 };
References InterfaceLoader::resolveInterface().
resolveObjectByDescriptor()
int ReferenceResolver::resolveObjectByDescriptor (string descriptor, MethodArea * m_a) static private
Definition at line 44 of file reference_resolver.cpp.
{
   if(descriptor == "Ljava/lang/String;" ){
     string type;
     type += descriptor[0];
     JVMType p_type = ComponentType::getTypeFromDescriptor(type);
     ComponentType* newprimitive = ComponentType::getDefaultValue(p_type);
     return Heap::getInstance()->storeComponent(newprimitive);
   }
   if(descriptor[0] == 'L'){
     string class_name;
     for(size_t j=1;j<descriptor.size();j+=1){
       if(descriptor[j] == ';') break;
       class_name += descriptor[j];
     }
     ReferenceResolver::resolveClassName(class_name, m_a);
     JVMObject* newObject = new JVMObject(class_name);
     newObject->initializeFields();
     return  Heap::getInstance()->storeComponent(newObject);
   }
   return -1;
 }
References ComponentType::getDefaultValue(), Heap::getInstance(), ComponentType::getTypeFromDescriptor(), JVMObject::initializeFields(), resolveClassName(), and Heap::storeComponent().
Referenced by allocateArray().
resolveStaticFieldSymbolicReference()
JVMField * ReferenceResolver::resolveStaticFieldSymbolicReference (string symbolic_reference, MethodArea * method_area) static
Definition at line 22 of file reference_resolver.cpp.
{
   Heap* heap = Heap::getInstance();
   pair<string,string> names = ReferenceResolver::separateSymbol(symbolic_reference, ".");
   string class_name = names.first;
   string field_name = names.second;
   int class_ref = ClassLoader::resolveClass(class_name, method_area);
   JVMClass* resolved_class = (JVMClass*)heap->getReference(class_ref);
   JVMField* field = resolved_class->getField(field_name);
   return field;
 }
References JVMClass::getField(), Heap::getInstance(), Heap::getReference(), ClassLoader::resolveClass(), and separateSymbol().
Referenced by Instructions::GetStatic::execute(), and Instructions::PutStatic::execute().
resolveStringReference()
static int ReferenceResolver::resolveStringReference (string toResolve) static
separateSymbol()
pair< string, string > ReferenceResolver::separateSymbol (string str, string delimiter) static
Definition at line 10 of file reference_resolver.cpp.
{
   size_t delimiter_pos = str.find(".");
   string class_name = str.substr(0, delimiter_pos);
   str.erase(0, delimiter_pos+1);
   pair<string, string> ret;
   ret.first = class_name;
   ret.second = str;
   return ret;
 }
Referenced by Instructions::GetField::execute(), Instructions::InvokeStatic::execute(), Instructions::InvokeVirtual::execute(), Instructions::PutField::execute(), Instructions::GetStatic::execute(), Instructions::InvokeSpecial::execute(), and resolveStaticFieldSymbolicReference().
The documentation for this class was generated from the following files:
include/interpretador/reference_resolver.hpp
src/interpretador/reference_resolver.cpp