SB-2020-2-JVM: Instructions::Wide Class Reference
Instructions::Wide Class Reference
#include <wide.hpp>
Public Member Functions
Wide (Attribute::CodeAttribute *code_attr, uint8_t opcode)
void print (int)
~Wide ()
Public Member Functions inherited from Instructions::BaseInstruction
BaseInstruction (Attribute::CodeAttribute *code_attr, uint8_t opcode)
virtual ~BaseInstruction ()
virtual void print ()
virtual string toString ()
virtual int execute (Frame *frame)
Data Fields
uint8_t instruction_opcode
Instructions::BaseInstruction * instruction
uint16_t index
uint16_t const_bytes
Data Fields inherited from Instructions::BaseInstruction
uint8_t opcode
uint16_t pc
Additional Inherited Members
Static Public Member Functions inherited from Instructions::BaseInstruction
static string getTypePrefix (uint8_t type)
static BaseInstruction * getInstance (Attribute::CodeAttribute *code_attr, uint8_t opcode, uint32_t pc)
Protected Member Functions inherited from Instructions::BaseInstruction
string hexToString (int)
string intToString (int)
string intToSignedString (int)
string createStringWithCPRef (string name, uint16_t index)
string tabs (int)
Protected Attributes inherited from Instructions::BaseInstruction
Attribute::CodeAttribute * code_attr
Detailed Description
Definition at line 8 of file wide.hpp.
Constructor & Destructor Documentation
Wide()
Wide::Wide (Attribute::CodeAttribute * code_attr, uint8_t opcode)
Definition at line 6 of file wide.cpp.
     :BaseInstruction(code_attr, opcode){
     FileReader *f = this->code_attr->class_file->file_reader;
     f->readBytes(1, this->instruction_opcode);
     BaseInstruction::getInstance(this->code_attr, this->instruction_opcode, 0);
     f->readBytes(2, this->index);
     if(this->instruction_opcode == 0x84){ // iinc
       f->readBytes(2, this->const_bytes);
     }
 }
References AttributeInfo::class_file, const_bytes, ClassFile::file_reader, Instructions::BaseInstruction::getInstance(), index, instruction_opcode, and FileReader::readBytes().
~Wide()
Wide::~Wide ()
Definition at line 24 of file wide.cpp.
            {
   delete this->instruction;
 }
References instruction.
Member Function Documentation
print()
void Wide::print (int n_tabs) virtual
Reimplemented from Instructions::BaseInstruction.
Definition at line 18 of file wide.cpp.
{
   cout << "wide -> " + this->instruction->toString()
   + "; #" + this->intToString(this->index) +
   this->code_attr->class_file->getConstantPoolEntry(this->index)->toString();
 }
References AttributeInfo::class_file, Instructions::BaseInstruction::code_attr, ClassFile::getConstantPoolEntry(), index, instruction, Instructions::BaseInstruction::intToString(), Instructions::BaseInstruction::toString(), and CpInfo::toString().
Field Documentation
const_bytes
uint16_t Instructions::Wide::const_bytes
Definition at line 13 of file wide.hpp.
Referenced by Wide().
index
uint16_t Instructions::Wide::index
Definition at line 12 of file wide.hpp.
Referenced by print(), and Wide().
instruction
Instructions::BaseInstruction* Instructions::Wide::instruction
Definition at line 11 of file wide.hpp.
Referenced by print(), and ~Wide().
instruction_opcode
uint8_t Instructions::Wide::instruction_opcode
Definition at line 10 of file wide.hpp.
Referenced by Wide().
The documentation for this class was generated from the following files:
include/attribute_info_classes/instruction_classes/wide.hpp
src/attribute_info_classes/instruction_classes/wide.cpp