SB-2020-2-JVM: CpInfo Class Reference
CpInfo Class Reference abstract
#include <cp_info.hpp>
Public Member Functions
CpInfo (ClassFile *class_file)
virtual ~CpInfo ()
virtual void setInfo ()=0
virtual void printInfo ()=0
virtual string toString ()
virtual uint64_t getValue ()
Static Public Member Functions
static CpInfo * returnUnusableSpace (ClassFile *class_file)
static CpInfo * getInstance (uint8_t tag, ClassFile *class_file)
static CpInfo * getUtf8 (vector< CpInfo * > constant_pool, int index)
Data Fields
uint8_t tag
Protected Attributes
ClassFile * class_file
Detailed Description
Definition at line 12 of file cp_info.hpp.
Constructor & Destructor Documentation
CpInfo()
CpInfo::CpInfo (ClassFile * class_file)
Definition at line 18 of file cp_info.cpp.
{
   this->class_file = class_file;
 }
References class_file.
~CpInfo()
virtual CpInfo::~CpInfo () inline virtual
Definition at line 19 of file cp_info.hpp.
 { };
Member Function Documentation
getInstance()
CpInfo * CpInfo::getInstance (uint8_t tag, ClassFile * class_file) static
Definition at line 35 of file cp_info.cpp.
{
   CpInfo* correct_instance;
   switch (tag){
   case 0x1:
     correct_instance = new CP::Utf8Info(class_file);
     break;
   case 0x3:
     correct_instance = new CP::IntegerInfo(class_file);
     break;
   case 0x4:
     correct_instance = new CP::FloatInfo(class_file);
     break;
   case 0x5:
     correct_instance = new CP::LongInfo(class_file);
     break;
   case 0x6:
     correct_instance = new CP::DoubleInfo(class_file);
     break;
   case 0x7:
     correct_instance = new CP::ClassInfo(class_file);
     break;
   case 0x8:
     correct_instance = new CP::StringInfo(class_file);
     break;
   case 0x9:
     correct_instance = new CP::FieldRefInfo(class_file);
     break;
   case 0xa:
     correct_instance = new CP::MethodRefInfo(class_file);
     break;
   case 0xb:
     correct_instance = new CP::InterfaceMethodRefInfo(class_file);
     break;
   case 0xc:
     correct_instance = new CP::NameAndTypeInfo(class_file);
     break;
   case 0xf:
     correct_instance = new CP::MethodHandleInfo(class_file);
     break;
   case 0x10:
     correct_instance = new CP::MethodTypeInfo(class_file);
     break;
   case 0x12:
     correct_instance = new CP::InvokeDynamicInfo(class_file);
     break;
   default:
     correct_instance =  new CP::UnusedInfo(class_file);
     // throw std::invalid_argument("Invalid CP Tag");
     break;
   }
   return correct_instance;
 }
References class_file, and tag.
Referenced by ClassFile::loadConstantPool().
getUtf8()
static CpInfo* CpInfo::getUtf8 (vector< CpInfo * > constant_pool, int index) static
getValue()
uint64_t CpInfo::getValue () virtual
Reimplemented in CP::DoubleInfo.
Definition at line 30 of file cp_info.cpp.
{
   cout << "AVISO getvalue nao implementado" << endl;
   return 0;
 }
printInfo()
virtual void CpInfo::printInfo () pure virtual
Implemented in CP::Utf8Info, CP::UnusedInfo, CP::StringInfo, CP::NameAndTypeInfo, CP::MethodTypeInfo, CP::MethodRefInfo, CP::MethodHandleInfo, CP::LongInfo, CP::InvokeDynamicInfo, CP::InterfaceMethodRefInfo, CP::IntegerInfo, CP::FloatInfo, CP::FieldRefInfo, CP::DoubleInfo, and CP::ClassInfo.
returnUnusableSpace()
CpInfo * CpInfo::returnUnusableSpace (ClassFile * class_file) static
Definition at line 22 of file cp_info.cpp.
{
     return new CP::UnusedInfo(class_file);
 }
References class_file.
Referenced by ClassFile::loadConstantPool().
setInfo()
virtual void CpInfo::setInfo () pure virtual
Implemented in CP::Utf8Info, CP::UnusedInfo, CP::StringInfo, CP::NameAndTypeInfo, CP::MethodTypeInfo, CP::MethodRefInfo, CP::MethodHandleInfo, CP::LongInfo, CP::InvokeDynamicInfo, CP::InterfaceMethodRefInfo, CP::IntegerInfo, CP::FloatInfo, CP::FieldRefInfo, CP::DoubleInfo, and CP::ClassInfo.
Referenced by ClassFile::loadConstantPool().
toString()
string CpInfo::toString () virtual
Reimplemented in CP::Utf8Info, CP::StringInfo, CP::NameAndTypeInfo, CP::MethodTypeInfo, CP::MethodRefInfo, CP::LongInfo, CP::IntegerInfo, CP::FloatInfo, CP::FieldRefInfo, CP::DoubleInfo, and CP::ClassInfo.
Definition at line 26 of file cp_info.cpp.
{
   return "<not implemented>";
 }
Referenced by Instructions::BaseInstruction::createStringWithCPRef(), Instructions::GetField::execute(), Instructions::New::execute(), Instructions::PutField::execute(), Instructions::ANewArray::execute(), Instructions::GetStatic::execute(), Instructions::Ldc::execute(), Instructions::MultiANewArray::execute(), Instructions::PutStatic::execute(), FieldInfo::getDescriptor(), MethodInfo::getDescriptorString(), FieldInfo::getName(), MethodInfo::getName(), ClassFile::getSuperClassName(), ClassFile::getThisClassName(), Instructions::Wide::print(), ClassFile::printClass(), FieldInfo::printInfo(), InterfaceInfo::printInfo(), MethodInfo::printInfo(), Instructions::GetStatic::toString(), Instructions::Ldc::toString(), Instructions::LdcW::toString(), Instructions::Ldc2W::toString(), Instructions::PutStatic::toString(), and CP::StringInfo::toString().
Field Documentation
class_file
ClassFile* CpInfo::class_file protected
Definition at line 14 of file cp_info.hpp.
Referenced by CpInfo(), getInstance(), and returnUnusableSpace().
tag
uint8_t CpInfo::tag
Definition at line 17 of file cp_info.hpp.
Referenced by CP::ClassInfo::ClassInfo(), CP::DoubleInfo::DoubleInfo(), Instructions::Ldc::execute(), Instructions::LdcW::execute(), Instructions::Ldc2W::execute(), CP::FieldRefInfo::FieldRefInfo(), CP::FloatInfo::FloatInfo(), getInstance(), CP::IntegerInfo::IntegerInfo(), CP::InterfaceMethodRefInfo::InterfaceMethodRefInfo(), CP::InvokeDynamicInfo::InvokeDynamicInfo(), CP::LongInfo::LongInfo(), CP::MethodHandleInfo::MethodHandleInfo(), CP::MethodRefInfo::MethodRefInfo(), CP::MethodTypeInfo::MethodTypeInfo(), CP::NameAndTypeInfo::NameAndTypeInfo(), CP::StringInfo::StringInfo(), CP::UnusedInfo::UnusedInfo(), and CP::Utf8Info::Utf8Info().
The documentation for this class was generated from the following files:
include/cp_info.hpp
src/cp_info.cpp