SB-2020-2-JVM: MethodInfo Class Reference
MethodInfo Class Reference
#include <method_info.hpp>
Public Member Functions
MethodInfo (ClassFile *class_file)
~MethodInfo ()
Attribute::CodeAttribute * getCode ()
Instructions::BaseInstruction * getInstruction (int pc)
string getDescriptorString ()
int getArgsCount ()
string getName ()
void printInfo ()
Static Public Member Functions
static int getArgsCountOn (string descriptor)
Data Fields
ClassFile * class_file
Private Attributes
uint16_t access_flags
uint16_t name_index
uint16_t descriptor_index
uint16_t attributes_count
vector< AttributeInfo * > attributes
Detailed Description
Definition at line 14 of file method_info.hpp.
Constructor & Destructor Documentation
MethodInfo()
MethodInfo::MethodInfo (ClassFile * class_file)
Definition at line 5 of file method_info.cpp.
{
     this->class_file = class_file;
     this->class_file->file_reader->readBytes(2, this->access_flags);
     this->class_file->file_reader->readBytes(2, this->name_index);
     this->class_file->file_reader->readBytes(2, this->descriptor_index);
     this->class_file->file_reader->readBytes(2, this->attributes_count);
     AttributeInfo::loadAttributes(this->attributes, this->attributes_count, this->class_file);
 }
References access_flags, attributes, attributes_count, class_file, descriptor_index, ClassFile::file_reader, AttributeInfo::loadAttributes(), name_index, and FileReader::readBytes().
~MethodInfo()
MethodInfo::~MethodInfo ()
Definition at line 14 of file method_info.cpp.
{
   this->class_file->deleteVector(this->attributes);
 }
References attributes, class_file, and ClassFile::deleteVector().
Member Function Documentation
getArgsCount()
int MethodInfo::getArgsCount ()
Definition at line 71 of file method_info.cpp.
{
   string descriptor = this->getDescriptorString();
   return MethodInfo::getArgsCountOn(descriptor);
 }
References getArgsCountOn(), and getDescriptorString().
Referenced by Thread::invokeInstanceMethod(), and Thread::invokeStaticMethod().
getArgsCountOn()
int MethodInfo::getArgsCountOn (string descriptor) static
Definition at line 46 of file method_info.cpp.
{
    // TODO: codar isso direito
   string types = "BCDFIJSZ";
   int n_args = 0;
   size_t i, j;
   for(i=0;i<descriptor.size();i+=1){
     if(descriptor[i] == ')') break;
     if(types.find(descriptor[i]) != string::npos){
       n_args++;
       continue;
     }
     if( descriptor[i] == 'L'){
       for(j=i;j<descriptor.size();j+=1){
         if(descriptor[j] == ';') break;
       }
       n_args++;
       i = j;
     }
   }
   return n_args;
 }
Referenced by InvokeSimulation::exceptionInit(), getArgsCount(), InvokeSimulation::println(), and InvokeSimulation::stringMethod().
getCode()
Attribute::CodeAttribute * MethodInfo::getCode ()
Definition at line 22 of file method_info.cpp.
{
   for(uint32_t i=0;i<this->attributes.size();i+=1){
     if(this->attributes[i]->getAttributeName() == "Code")
       return (Attribute::CodeAttribute*) this->attributes[i];
   }
   throw runtime_error("Metodo sem atributo Code!");
 }
References attributes.
Referenced by Frame::Frame(), getInstruction(), and Thread::start().
getDescriptorString()
string MethodInfo::getDescriptorString ()
Definition at line 42 of file method_info.cpp.
{
   return this->class_file->getConstantPoolEntry(this->descriptor_index)->toString();
 }
References class_file, descriptor_index, ClassFile::getConstantPoolEntry(), and CpInfo::toString().
Referenced by getArgsCount(), and MethodArea::getMethodByName().
getInstruction()
Instructions::BaseInstruction * MethodInfo::getInstruction (int pc)
Definition at line 30 of file method_info.cpp.
{
   return this->getCode()->getInstructionByPc(pc);
 }
References getCode(), and Attribute::CodeAttribute::getInstructionByPc().
Referenced by Frame::runInstruction().
getName()
string MethodInfo::getName ()
Definition at line 18 of file method_info.cpp.
{
   return this->class_file->getConstantPoolEntry(this->name_index)->toString();
 }
References class_file, ClassFile::getConstantPoolEntry(), name_index, and CpInfo::toString().
Referenced by MethodArea::getMethodByName(), MethodArea::searchMainMethod(), and Thread::start().
printInfo()
void MethodInfo::printInfo ()
Definition at line 34 of file method_info.cpp.
{
   cout << dec;
   cout << "\tName:              cpinfo #" << this->name_index << " <" << this->class_file->getConstantPoolEntry(this->name_index)->toString() << ">" << endl;
   cout << "\tDescriptor:        cpinfo #" << this->descriptor_index << " <" << this->class_file->getConstantPoolEntry(this->descriptor_index)->toString() << ">" << endl;
   cout << "\tAccess flags:      0x" << hex << this->access_flags << " " << this->class_file->beautifiedAccessFlags(this->access_flags, false, true) << endl;
   AttributeInfo::printAttributes(this->attributes, 2);
 }
References access_flags, attributes, ClassFile::beautifiedAccessFlags(), class_file, descriptor_index, ClassFile::getConstantPoolEntry(), name_index, AttributeInfo::printAttributes(), and CpInfo::toString().
Field Documentation
access_flags
uint16_t MethodInfo::access_flags private
Definition at line 16 of file method_info.hpp.
Referenced by MethodInfo(), and printInfo().
attributes
vector<AttributeInfo*> MethodInfo::attributes private
Definition at line 20 of file method_info.hpp.
Referenced by getCode(), MethodInfo(), printInfo(), and ~MethodInfo().
attributes_count
uint16_t MethodInfo::attributes_count private
Definition at line 19 of file method_info.hpp.
Referenced by MethodInfo().
class_file
ClassFile* MethodInfo::class_file
Definition at line 23 of file method_info.hpp.
Referenced by InvokeSimulation::exceptionInit(), Instructions::GetField::execute(), Instructions::InvokeStatic::execute(), Instructions::InvokeVirtual::execute(), Instructions::New::execute(), Instructions::PutField::execute(), Instructions::GetStatic::execute(), Instructions::InvokeSpecial::execute(), Instructions::PutStatic::execute(), getDescriptorString(), getName(), Thread::handleException(), MethodInfo(), printInfo(), InvokeSimulation::println(), ExecutionEngine::start(), InvokeSimulation::stringMethod(), and ~MethodInfo().
descriptor_index
uint16_t MethodInfo::descriptor_index private
Definition at line 18 of file method_info.hpp.
Referenced by getDescriptorString(), MethodInfo(), and printInfo().
name_index
uint16_t MethodInfo::name_index private
Definition at line 17 of file method_info.hpp.
Referenced by getName(), MethodInfo(), and printInfo().
The documentation for this class was generated from the following files:
include/method_info.hpp
src/method_info.cpp