SB-2020-2-JVM: Instructions::ANewArray Class Reference
Instructions::ANewArray Class Reference
#include <anewarray.hpp>
Public Member Functions
ANewArray (Attribute::CodeAttribute *code_attr, uint8_t opcode)
string toString ()
int execute (Frame *frame)
Public Member Functions inherited from Instructions::BaseInstruction
BaseInstruction (Attribute::CodeAttribute *code_attr, uint8_t opcode)
virtual ~BaseInstruction ()
virtual void print ()
virtual void print (int)
Data Fields
uint16_t index
Data Fields inherited from Instructions::BaseInstruction
uint8_t opcode
uint16_t pc
Additional Inherited Members
Static Public Member Functions inherited from Instructions::BaseInstruction
static string getTypePrefix (uint8_t type)
static BaseInstruction * getInstance (Attribute::CodeAttribute *code_attr, uint8_t opcode, uint32_t pc)
Protected Member Functions inherited from Instructions::BaseInstruction
string hexToString (int)
string intToString (int)
string intToSignedString (int)
string createStringWithCPRef (string name, uint16_t index)
string tabs (int)
Protected Attributes inherited from Instructions::BaseInstruction
Attribute::CodeAttribute * code_attr
Detailed Description
Definition at line 8 of file anewarray.hpp.
Constructor & Destructor Documentation
ANewArray()
ANewArray::ANewArray (Attribute::CodeAttribute * code_attr, uint8_t opcode)
Definition at line 7 of file anewarray.cpp.
     :BaseInstruction(code_attr, opcode){
   FileReader *f_reader = this->code_attr->class_file->file_reader;
   f_reader->readBytes(2, this->index);
 }
References AttributeInfo::class_file, ClassFile::file_reader, index, and FileReader::readBytes().
Member Function Documentation
execute()
int ANewArray::execute (Frame * frame) virtual
Reimplemented from Instructions::BaseInstruction.
Definition at line 17 of file anewarray.cpp.
{
     vector<uint64_t> dims;
     dims.push_back(frame->operand_stack.pop().first);
     string class_name = this->code_attr->class_file->getConstantPoolEntry(this->index)->toString();
     int heap_ref = ReferenceResolver::allocateArray("[L"+class_name+ ";", frame->thread->method_area, dims);
     frame->operand_stack.push(heap_ref, Reference);
     return frame->local_pc+=3;
 }
References ReferenceResolver::allocateArray(), AttributeInfo::class_file, Instructions::BaseInstruction::code_attr, ClassFile::getConstantPoolEntry(), index, Frame::local_pc, Thread::method_area, Frame::operand_stack, OperandStack::pop(), OperandStack::push(), Reference, Frame::thread, and CpInfo::toString().
toString()
string ANewArray::toString () virtual
Reimplemented from Instructions::BaseInstruction.
Definition at line 13 of file anewarray.cpp.
{
   return this->createStringWithCPRef("anewarray", this->index);
 }
References Instructions::BaseInstruction::createStringWithCPRef(), and index.
Field Documentation
index
uint16_t Instructions::ANewArray::index
Definition at line 10 of file anewarray.hpp.
Referenced by ANewArray(), execute(), and toString().
The documentation for this class was generated from the following files:
include/attribute_info_classes/instruction_classes/anewarray.hpp
src/attribute_info_classes/instruction_classes/anewarray.cpp