SB-2020-2-JVM: Instructions::New Class Reference
Instructions::New Class Reference
#include <new.hpp>
Public Member Functions
New (Attribute::CodeAttribute *code_attr, uint8_t opcode)
string toString ()
int execute (Frame *)
Public Member Functions inherited from Instructions::BaseInstruction
BaseInstruction (Attribute::CodeAttribute *code_attr, uint8_t opcode)
virtual ~BaseInstruction ()
virtual void print ()
virtual void print (int)
Private Attributes
uint16_t index
Additional Inherited Members
Static Public Member Functions inherited from Instructions::BaseInstruction
static string getTypePrefix (uint8_t type)
static BaseInstruction * getInstance (Attribute::CodeAttribute *code_attr, uint8_t opcode, uint32_t pc)
Data Fields inherited from Instructions::BaseInstruction
uint8_t opcode
uint16_t pc
Protected Member Functions inherited from Instructions::BaseInstruction
string hexToString (int)
string intToString (int)
string intToSignedString (int)
string createStringWithCPRef (string name, uint16_t index)
string tabs (int)
Protected Attributes inherited from Instructions::BaseInstruction
Attribute::CodeAttribute * code_attr
Detailed Description
Definition at line 8 of file new.hpp.
Constructor & Destructor Documentation
New()
New::New (Attribute::CodeAttribute * code_attr, uint8_t opcode)
Definition at line 10 of file new.cpp.
     :BaseInstruction(code_attr, opcode){
   FileReader *f_reader = this->code_attr->class_file->file_reader;
   f_reader->readBytes(2, this->index);
 }
References AttributeInfo::class_file, ClassFile::file_reader, index, and FileReader::readBytes().
Member Function Documentation
execute()
int New::execute (Frame * frame) virtual
Reimplemented from Instructions::BaseInstruction.
Definition at line 20 of file new.cpp.
{
   MethodArea* m = frame->thread->method_area;
   string class_name = frame->current_method->class_file->getConstantPoolEntry(this->index)->toString();
   if(ReferenceResolver::resolveClassName(class_name, m) >= 0){
     JVMObject* newObject = new JVMObject(class_name);
     newObject->initializeFields();
     int heap_ref = Heap::getInstance()->storeComponent(newObject);
     frame->operand_stack.push(heap_ref, Reference);
   }
   else if(class_name == "java/lang/String" || class_name == "java/lang/StringBuilder"){
     StringType* newString = new StringType("");
     int heap_ref = Heap::getInstance()->storeComponent(newString);
     frame->operand_stack.push(heap_ref, Reference);
   }
   else if (class_name.find("Exception") != std::string::npos || class_name.find("Error") != std::string::npos) {
     ExceptionType* e = new ExceptionType(class_name);
     int heap_ref = Heap::getInstance()->storeComponent(e);
     frame->operand_stack.push(heap_ref, Reference);
   }
   else{
     frame->operand_stack.push(-1, Reference);
   }
   frame->local_pc+=3;
   return frame->local_pc;
 }
References MethodInfo::class_file, Frame::current_method, ClassFile::getConstantPoolEntry(), Heap::getInstance(), index, JVMObject::initializeFields(), Frame::local_pc, Thread::method_area, Frame::operand_stack, OperandStack::push(), Reference, ReferenceResolver::resolveClassName(), Heap::storeComponent(), Frame::thread, and CpInfo::toString().
toString()
string New::toString () virtual
Reimplemented from Instructions::BaseInstruction.
Definition at line 16 of file new.cpp.
                     {
   return this->createStringWithCPRef("new", this->index);
 }
References Instructions::BaseInstruction::createStringWithCPRef(), and index.
Field Documentation
index
uint16_t Instructions::New::index private
Definition at line 10 of file new.hpp.
Referenced by execute(), New(), and toString().
The documentation for this class was generated from the following files:
include/attribute_info_classes/instruction_classes/new.hpp
src/attribute_info_classes/instruction_classes/new.cpp