SB-2020-2-JVM: Instructions::AbstractStore Class Reference
Instructions::AbstractStore Class Reference abstract
#include <_store.hpp>
Public Member Functions
AbstractStore (Attribute::CodeAttribute *code_attr, uint8_t opcode, uint8_t _store_opcode, uint8_t _storen_base_opcode)
int execute (Frame *frame)
virtual string getName ()=0
virtual JVMType getType ()=0
string toString ()
Public Member Functions inherited from Instructions::BaseInstruction
BaseInstruction (Attribute::CodeAttribute *code_attr, uint8_t opcode)
virtual ~BaseInstruction ()
virtual void print ()
virtual void print (int)
Protected Attributes
bool is_n_class
uint8_t param
Protected Attributes inherited from Instructions::BaseInstruction
Attribute::CodeAttribute * code_attr
Additional Inherited Members
Static Public Member Functions inherited from Instructions::BaseInstruction
static string getTypePrefix (uint8_t type)
static BaseInstruction * getInstance (Attribute::CodeAttribute *code_attr, uint8_t opcode, uint32_t pc)
Data Fields inherited from Instructions::BaseInstruction
uint8_t opcode
uint16_t pc
Protected Member Functions inherited from Instructions::BaseInstruction
string hexToString (int)
string intToString (int)
string intToSignedString (int)
string createStringWithCPRef (string name, uint16_t index)
string tabs (int)
Detailed Description
Definition at line 9 of file _store.hpp.
Constructor & Destructor Documentation
AbstractStore()
AbstractStore::AbstractStore (Attribute::CodeAttribute * code_attr, uint8_t opcode, uint8_t _store_opcode, uint8_t _storen_base_opcode)
Definition at line 4 of file _store.cpp.
     : BaseInstruction(code_attr, opcode)
 {
   this->is_n_class = !(opcode == _store_opcode);
   if (!this->is_n_class)
     this->code_attr->class_file->file_reader->readBytes(1, this->param);
   else
     this->param = this->opcode - _storen_base_opcode;
 }
References AttributeInfo::class_file, ClassFile::file_reader, is_n_class, param, and FileReader::readBytes().
Member Function Documentation
execute()
int AbstractStore::execute (Frame * frame) virtual
Reimplemented from Instructions::BaseInstruction.
Definition at line 16 of file _store.cpp.
{
   uint64_t value = frame->operand_stack.pop().first;
   frame->local_variables.insert(this->param, value, this->getType());
   if (this->is_n_class)
     frame->local_pc += 1;
   else
     frame->local_pc += 2;
   return frame->local_pc;
 }
References getType(), LocalVariable::insert(), is_n_class, Frame::local_pc, Frame::local_variables, Frame::operand_stack, param, and OperandStack::pop().
getName()
virtual string Instructions::AbstractStore::getName () pure virtual
Implemented in Instructions::Astore, Instructions::Dstore, Instructions::Fstore, Instructions::Lstore, and Instructions::Istore.
Referenced by toString().
getType()
virtual JVMType Instructions::AbstractStore::getType () pure virtual
Implemented in Instructions::Astore, Instructions::Dstore, Instructions::Fstore, Instructions::Lstore, and Instructions::Istore.
Referenced by execute().
toString()
string AbstractStore::toString () virtual
Reimplemented from Instructions::BaseInstruction.
Definition at line 28 of file _store.cpp.
 {
   if (this->is_n_class)
     return this->getName() + "_" + this->hexToString(this->param);
   else
     return this->getName() + " " + this->hexToString(this->param);
 }
References getName(), Instructions::BaseInstruction::hexToString(), is_n_class, and param.
Field Documentation
is_n_class
bool Instructions::AbstractStore::is_n_class protected
Definition at line 11 of file _store.hpp.
Referenced by AbstractStore(), execute(), and toString().
param
uint8_t Instructions::AbstractStore::param protected
Definition at line 12 of file _store.hpp.
Referenced by AbstractStore(), execute(), and toString().
The documentation for this class was generated from the following files:
include/attribute_info_classes/instruction_classes/_store.hpp
src/attribute_info_classes/instruction_classes/_store.cpp