SB-2020-2-JVM: CP::MethodRefInfo Class Reference
CP::MethodRefInfo Class Reference
#include <method_ref_info.hpp>
Public Member Functions
MethodRefInfo (ClassFile *class_file)
void setInfo ()
void printInfo ()
string toString ()
string getDescriptor ()
Public Member Functions inherited from CpInfo
CpInfo (ClassFile *class_file)
virtual ~CpInfo ()
virtual uint64_t getValue ()
Private Attributes
uint16_t class_index
uint16_t name_and_type_index
Additional Inherited Members
Static Public Member Functions inherited from CpInfo
static CpInfo * returnUnusableSpace (ClassFile *class_file)
static CpInfo * getInstance (uint8_t tag, ClassFile *class_file)
static CpInfo * getUtf8 (vector< CpInfo * > constant_pool, int index)
Data Fields inherited from CpInfo
uint8_t tag
Protected Attributes inherited from CpInfo
ClassFile * class_file
Detailed Description
Definition at line 8 of file method_ref_info.hpp.
Constructor & Destructor Documentation
MethodRefInfo()
CP::MethodRefInfo::MethodRefInfo (ClassFile * class_file)
Definition at line 5 of file method_ref_info.cpp.
                                                     : CpInfo(class_file){
   this->tag = 10;
 }
References CpInfo::tag.
Member Function Documentation
getDescriptor()
string CP::MethodRefInfo::getDescriptor ()
Definition at line 22 of file method_ref_info.cpp.
{
   CP::NameAndTypeInfo* name_info = (CP::NameAndTypeInfo*)this->class_file->getConstantPoolEntry((int)this->name_and_type_index);
   return name_info->getDescriptor();
 }
References CP::NameAndTypeInfo::getDescriptor().
Referenced by InvokeSimulation::exceptionInit(), Instructions::InvokeStatic::execute(), Instructions::InvokeVirtual::execute(), Instructions::InvokeSpecial::execute(), InvokeSimulation::println(), and InvokeSimulation::stringMethod().
printInfo()
void CP::MethodRefInfo::printInfo () virtual
Implements CpInfo.
Definition at line 27 of file method_ref_info.cpp.
{
   cout << "\tMethodRef: Class Index cp_info#" << this->class_index << " <" << this->class_file->getConstantPoolEntry((int)this->class_index)->toString() << ">";
   cout << "\n\tMethodRef: Name and Type Index cp_info#" << this->name_and_type_index << " <" << this->class_file->getConstantPoolEntry((int)this->name_and_type_index)->toString() << ">" << endl;
 }
setInfo()
void CP::MethodRefInfo::setInfo () virtual
Implements CpInfo.
Definition at line 9 of file method_ref_info.cpp.
{
   this->class_file->setAttribute<uint16_t>(2, this->class_index);
   this->class_file->setAttribute<uint16_t>(2, this->name_and_type_index);
 }
toString()
string CP::MethodRefInfo::toString () virtual
Reimplemented from CpInfo.
Definition at line 14 of file method_ref_info.cpp.
{
   string className = this->class_file->getConstantPoolEntry(this->class_index)->toString();
   string methodName =  this->class_file->getConstantPoolEntry(this->name_and_type_index)->toString();
   string methodNameParsed = methodName.substr(0, methodName.find(":"));
   return className + "." + methodNameParsed;
 }
Referenced by Instructions::InvokeStatic::execute(), Instructions::InvokeVirtual::execute(), and Instructions::InvokeSpecial::execute().
Field Documentation
class_index
uint16_t CP::MethodRefInfo::class_index private
Definition at line 9 of file method_ref_info.hpp.
name_and_type_index
uint16_t CP::MethodRefInfo::name_and_type_index private
Definition at line 10 of file method_ref_info.hpp.
The documentation for this class was generated from the following files:
include/constant_pool_classes/method_ref_info.hpp
src/constant_pool_classes/method_ref_info.cpp