SB-2020-2-JVM: JVMField Class Reference
JVMField Class Reference
#include <jvm_field.hpp>
Public Member Functions
JVMField (FieldInfo *)
void setData (ComponentType *)
ComponentType * getData ()
string toString ()
Public Member Functions inherited from ComponentType
ComponentType (JVMType component_type)
void setReference (int)
int getReference ()
virtual void print ()
virtual ~ComponentType ()
Data Fields
FieldInfo * field_info_ref
string field_name
Data Fields inherited from ComponentType
JVMType type
Private Attributes
ComponentType * data
JVMType field_type
Additional Inherited Members
Static Public Member Functions inherited from ComponentType
static ComponentType * getDefaultValue (JVMType)
static JVMType getTypeFromDescriptor (string descriptor)
Protected Attributes inherited from ComponentType
int heap_reference
Detailed Description
Definition at line 11 of file jvm_field.hpp.
Constructor & Destructor Documentation
JVMField()
JVMField::JVMField (FieldInfo * field_info)
Definition at line 7 of file jvm_field.cpp.
                                        :ComponentType(JVMFIELD){
   this->field_info_ref = field_info;
   this->field_name = field_info->getName();
   string field_descriptor = field_info->getDescriptor();
   JVMType type = ComponentType::getTypeFromDescriptor(field_descriptor);
   this->data = ComponentType::getDefaultValue(type);
   Heap::getInstance()->storeComponent(this->data);
 }
References data, field_info_ref, field_name, ComponentType::getDefaultValue(), FieldInfo::getDescriptor(), Heap::getInstance(), FieldInfo::getName(), ComponentType::getTypeFromDescriptor(), Heap::storeComponent(), and ComponentType::type.
Member Function Documentation
getData()
ComponentType * JVMField::getData ()
Definition at line 22 of file jvm_field.cpp.
{
   return this->data;
 };
References data.
Referenced by Instructions::GetField::execute(), and Instructions::GetStatic::execute().
setData()
void JVMField::setData (ComponentType * newData)
Definition at line 26 of file jvm_field.cpp.
{
   // TODO: fazer checagem de tipo dinamica
   if(newData->type != this->data->type ){
     throw std::runtime_error("TypeError: tipo atribuido ao field invalido");
   }
   Heap* heap = Heap::getInstance();
   heap->storeComponent(newData);
   this->data = newData;
 }
References data, Heap::getInstance(), Heap::storeComponent(), and ComponentType::type.
Referenced by Instructions::PutField::execute(), and Instructions::PutStatic::execute().
toString()
string JVMField::toString () virtual
Reimplemented from ComponentType.
Definition at line 18 of file jvm_field.cpp.
{
   return this->field_name;
 }
References field_name.
Field Documentation
data
ComponentType* JVMField::data private
Definition at line 13 of file jvm_field.hpp.
Referenced by getData(), JVMField(), and setData().
field_info_ref
FieldInfo* JVMField::field_info_ref
Definition at line 16 of file jvm_field.hpp.
Referenced by JVMObject::initializeFields(), and JVMField().
field_name
string JVMField::field_name
Definition at line 17 of file jvm_field.hpp.
Referenced by JVMField(), and toString().
field_type
JVMType JVMField::field_type private
Definition at line 14 of file jvm_field.hpp.
The documentation for this class was generated from the following files:
include/interpretador/types/jvm_field.hpp
src/interpretador/types/jvm_field.cpp