SB-2020-2-JVM: ArrayType Class Reference
ArrayType Class Reference
#include <array_type.hpp>
Public Member Functions
ArrayType (JVMType x)
void insert (ComponentType *)
void print ()
string toString ()
int getLength ()
void initialize (int max_length)
void setIndexAsPrimitiveType (int index, uint64_t value, JVMType type)
ComponentType * getIndex (int i)
pair< uint64_t, JVMType > getIndexAsAsPrimitiveType (int index)
int getIndexReference (int index)
Public Member Functions inherited from ComponentType
ComponentType (JVMType component_type)
void setReference (int)
int getReference ()
virtual ~ComponentType ()
Data Fields
JVMType content_type
Data Fields inherited from ComponentType
JVMType type
Private Attributes
vector< ComponentType * > data
int max_length
Additional Inherited Members
Static Public Member Functions inherited from ComponentType
static ComponentType * getDefaultValue (JVMType)
static JVMType getTypeFromDescriptor (string descriptor)
Protected Attributes inherited from ComponentType
int heap_reference
Detailed Description
Definition at line 12 of file array_type.hpp.
Constructor & Destructor Documentation
ArrayType()
ArrayType::ArrayType (JVMType x)
Definition at line 8 of file array_type.cpp.
                                         :ComponentType(JVMArray){
   this->content_type = content_type;
 }
References content_type.
Member Function Documentation
getIndex()
ComponentType * ArrayType::getIndex (int i)
Definition at line 58 of file array_type.cpp.
{
   if(i >= this->data.size() ) throw std::runtime_error("ArrayError: Acessando indice invalido");
   return this->data[i];
 }
References data.
Referenced by Instructions::InterfaceAload::execute().
getIndexAsAsPrimitiveType()
pair< uint64_t, JVMType > ArrayType::getIndexAsAsPrimitiveType (int index)
Definition at line 63 of file array_type.cpp.
{
   pair<uint64_t,JVMType> returnVal;
   PrimitiveType* p = (PrimitiveType*)this->data[index];
   returnVal.first = p->data;
   returnVal.second = p->type;
   return returnVal;
 }
References data, PrimitiveType::data, and ComponentType::type.
getIndexReference()
int ArrayType::getIndexReference (int index)
Definition at line 54 of file array_type.cpp.
{
   return this->data[index]->getReference();
 }
References data.
getLength()
int ArrayType::getLength ()
Definition at line 40 of file array_type.cpp.
{
   return this->data.size();
 }
References data.
Referenced by Instructions::ArrayLength::execute().
initialize()
void ArrayType::initialize (int max_length)
Definition at line 71 of file array_type.cpp.
{
     for (std::size_t i = 0; i < max_length; ++i) {
         ComponentType* default_value = ComponentType::getDefaultValue(this->content_type);
         this->insert(default_value);
     }
 }
References content_type, ComponentType::getDefaultValue(), insert(), and max_length.
Referenced by Instructions::NewArray::execute().
insert()
void ArrayType::insert (ComponentType * toinsert)
Definition at line 37 of file array_type.cpp.
{
   this->data.push_back(toinsert);
 }
References data.
Referenced by ReferenceResolver::allocateArray(), Heap::createPrimitiveTypeArray(), and initialize().
print()
void ArrayType::print () virtual
Reimplemented from ComponentType.
Definition at line 12 of file array_type.cpp.
                      {
   cout << "[";
   for(uint16_t i=0;i<this->data.size();i++){
     cout << this->data[i]->toString() << " (" << this->data[i]->type <<")";
     if(this->data[i]->type == Reference){
       PrimitiveType* p = (PrimitiveType*)this->data[i];
       ComponentType* ref = Heap::getInstance()->getReference(p->data);
       cout << "'" << ref->toString() << "'";
     }
     cout << ", ";
   }
   cout << "]" << endl;
 }
References data, PrimitiveType::data, Heap::getInstance(), Heap::getReference(), Reference, ComponentType::toString(), and ComponentType::type.
setIndexAsPrimitiveType()
void ArrayType::setIndexAsPrimitiveType (int index, uint64_t value, JVMType type)
Definition at line 43 of file array_type.cpp.
{
   if((uint)index > this->data.size()) throw std::runtime_error("ArrayError: Acessando indice invalido");
   if(type != this->content_type){
     // throw std::runtime_error("TypeError: Mudando elemento para tipo invalido");
   }
   ComponentType* oldValue = this->data[index];
   this->data[index] =  new PrimitiveType(value, type);
 }
References content_type, data, and ComponentType::type.
Referenced by Instructions::InterfaceAstore::execute().
toString()
string ArrayType::toString () virtual
Reimplemented from ComponentType.
Definition at line 26 of file array_type.cpp.
{
   stringstream paramString;
   paramString << "[";
   for(uint16_t i=0;i<this->data.size();i++){
     paramString << this->data[i]->toString();
     paramString << ", ";
   }
   paramString << "]";
   return paramString.str();
 }
References data.
Field Documentation
content_type
JVMType ArrayType::content_type
Definition at line 17 of file array_type.hpp.
Referenced by ArrayType(), initialize(), and setIndexAsPrimitiveType().
data
vector<ComponentType*> ArrayType::data private
Definition at line 14 of file array_type.hpp.
Referenced by getIndex(), getIndexAsAsPrimitiveType(), getIndexReference(), getLength(), insert(), print(), setIndexAsPrimitiveType(), and toString().
max_length
int ArrayType::max_length private
Definition at line 15 of file array_type.hpp.
Referenced by initialize().
The documentation for this class was generated from the following files:
include/interpretador/types/array_type.hpp
src/interpretador/types/array_type.cpp