SB-2020-2-JVM: Attribute::InnerClasses Class Reference
Attribute::InnerClasses Class Reference
#include <inner_classes.hpp>
Public Member Functions
InnerClasses (AttrInitialValue initial_val)
void printInfo (int n_tabs)
Public Member Functions inherited from AttributeInfo
AttributeInfo (Attribute::AttrInitialValue initial)
virtual ~AttributeInfo ()
string getAttributeName ()
Private Member Functions
void pushNewInnerClassStructure ()
Private Attributes
uint16_t number_of_classes
vector< InnerClassAttributes > classes
Additional Inherited Members
Static Public Member Functions inherited from AttributeInfo
static AttributeInfo * getInstance (ClassFile *class_file)
static string createTabs (int n_tabs)
static void loadAttributes (vector< AttributeInfo * > &attributes, uint16_t size, ClassFile *class_file)
static void printAttributes (vector< AttributeInfo * > attributes, int n_tabs)
Data Fields inherited from AttributeInfo
ClassFile * class_file
Protected Attributes inherited from AttributeInfo
uint16_t attribute_name_index
uint32_t attribute_length
Detailed Description
Definition at line 17 of file inner_classes.hpp.
Constructor & Destructor Documentation
InnerClasses()
InnerClasses::InnerClasses (AttrInitialValue initial_val)
Definition at line 5 of file inner_classes.cpp.
     :AttributeInfo(initial_value)
   {
   this->class_file->setAttribute(2, this->number_of_classes);
   for(int i=0;i<this->number_of_classes;i++){
     this->pushNewInnerClassStructure();
   }
 }
References AttributeInfo::class_file, number_of_classes, pushNewInnerClassStructure(), and ClassFile::setAttribute().
Member Function Documentation
printInfo()
void InnerClasses::printInfo (int n_tabs) virtual
Reimplemented from AttributeInfo.
Definition at line 14 of file inner_classes.cpp.
{
   AttributeInfo::printInfo(n_tabs);
   cout << createTabs(n_tabs+1) <<"Number of InnerClassses: " << this->number_of_classes << endl;
 }
References AttributeInfo::createTabs(), number_of_classes, and AttributeInfo::printInfo().
pushNewInnerClassStructure()
void InnerClasses::pushNewInnerClassStructure () private
Definition at line 19 of file inner_classes.cpp.
{
   InnerClassAttributes newAttribute;
   FileReader* f_reader = this->class_file->file_reader;
   f_reader->readBytes(2, newAttribute.inner_class_info_index);
   f_reader->readBytes(2, newAttribute.outer_class_info_index);
   f_reader->readBytes(2, newAttribute.inner_name_index);
   f_reader->readBytes(2, newAttribute.inner_class_access_flags);
   this->classes.push_back(newAttribute);
 }
References AttributeInfo::class_file, classes, ClassFile::file_reader, Attribute::InnerClassAttributes::inner_class_access_flags, Attribute::InnerClassAttributes::inner_class_info_index, Attribute::InnerClassAttributes::inner_name_index, Attribute::InnerClassAttributes::outer_class_info_index, and FileReader::readBytes().
Referenced by InnerClasses().
Field Documentation
classes
vector<InnerClassAttributes> Attribute::InnerClasses::classes private
Definition at line 20 of file inner_classes.hpp.
Referenced by pushNewInnerClassStructure().
number_of_classes
uint16_t Attribute::InnerClasses::number_of_classes private
Definition at line 19 of file inner_classes.hpp.
Referenced by InnerClasses(), and printInfo().
The documentation for this class was generated from the following files:
include/attribute_info_classes/inner_classes.hpp
src/attribute_info_classes/inner_classes.cpp