SB-2020-2-JVM: ClassLoader Class Reference
ClassLoader Class Reference
#include <class_loader.hpp>
Static Public Member Functions
static void loadClass (string class_name, MethodArea *)
static int resolveClass (string class_name, MethodArea *)
static PrimitiveType * resolveSymbol (Heap *, MethodArea *, string symbol)
Static Private Member Functions
static bool classIs (ClassFileState state, string class_name, MethodArea *method_area)
static bool classIsNot (ClassFileState state, string class_name, MethodArea *method_area)
static void linkClass (string class_name, MethodArea *)
static void initializeClass (string class_name, MethodArea *)
Detailed Description
Definition at line 14 of file class_loader.hpp.
Member Function Documentation
classIs()
bool ClassLoader::classIs (ClassFileState state, string class_name, MethodArea * method_area) static private
Definition at line 43 of file class_loader.cpp.
{
   try{
     ClassFile* class_file = method_area->getClassFile(class_name);
     return class_file->state >= state;
   }
   catch(const std::exception& e){
     return false;
   }
 }
References MethodArea::getClassFile(), and ClassFile::state.
Referenced by classIsNot().
classIsNot()
bool ClassLoader::classIsNot (ClassFileState state, string class_name, MethodArea * method_area) static private
Definition at line 53 of file class_loader.cpp.
{
   return !ClassLoader::classIs(state, class_name, method_area);
 }
References classIs().
Referenced by resolveClass().
initializeClass()
void ClassLoader::initializeClass (string class_name, MethodArea * method_area) static private
Definition at line 17 of file class_loader.cpp.
{
   ClassFile* class_file = method_area->getClassFile(class_name);
   class_file->state = INITIALIZED;
   if(method_area->classHasMethod(class_name, "<clinit>", "()V")){
     Thread newThread(method_area);
     newThread.invokeStaticMethod(class_name, "<clinit>", "()V");
     newThread.start();
   }
 }
References MethodArea::classHasMethod(), MethodArea::getClassFile(), INITIALIZED, Thread::invokeStaticMethod(), Thread::start(), and ClassFile::state.
Referenced by resolveClass().
linkClass()
void ClassLoader::linkClass (string class_name, MethodArea * method_area) static private
Definition at line 6 of file class_loader.cpp.
{
   Heap* heap = Heap::getInstance();
   JVMClass* linking_class = new JVMClass(class_name);
   linking_class->initializeFields();
   linking_class->class_file->heap_ref = heap->storeComponent(linking_class);
   linking_class->class_file->state = LINKED;
 }
References JVMClass::class_file, Heap::getInstance(), ClassFile::heap_ref, JVMClass::initializeFields(), LINKED, ClassFile::state, and Heap::storeComponent().
Referenced by resolveClass().
loadClass()
void ClassLoader::loadClass (string class_name, MethodArea * method_area) static
Definition at line 29 of file class_loader.cpp.
{
   ClassFile* inserted_class;
   string super_name = class_name;
   do{
     class_name = super_name;
     if(VERBOSE_CLASS_LOADER){
       cout << "CLASSLOADER: loading class " << class_name << endl;
     }
     inserted_class  = method_area->insertNewClass(class_name);
     super_name      = inserted_class->getSuperClassName();
   } while(class_name != "java/lang/Object");
 }
References ClassFile::getSuperClassName(), MethodArea::insertNewClass(), and VERBOSE_CLASS_LOADER.
Referenced by ExecutionEngine::loadMethodArea(), and resolveClass().
resolveClass()
int ClassLoader::resolveClass (string class_name, MethodArea * method_area) static
Definition at line 57 of file class_loader.cpp.
{
   if(ClassLoader::classIsNot(LOADED, class_name, method_area)){
     ClassLoader::loadClass(class_name, method_area);
   }
   if(ClassLoader::classIsNot(LINKED, class_name, method_area)){
     ClassLoader::linkClass(class_name, method_area);
   }
   if(ClassLoader::classIsNot(INITIALIZED, class_name, method_area)){
     ClassLoader::initializeClass(class_name, method_area);
   }
   // TODO: Resolver super-classes
   ClassFile* class_file = method_area->getClassFile(class_name);
   return class_file->heap_ref;
 }
References classIsNot(), MethodArea::getClassFile(), ClassFile::heap_ref, initializeClass(), INITIALIZED, linkClass(), LINKED, loadClass(), and LOADED.
Referenced by ReferenceResolver::resolveClassName(), and ReferenceResolver::resolveStaticFieldSymbolicReference().
resolveSymbol()
static PrimitiveType* ClassLoader::resolveSymbol (Heap * , MethodArea * , string symbol) static
The documentation for this class was generated from the following files:
include/interpretador/class_loader.hpp
src/interpretador/class_loader.cpp