SB-2020-2-JVM: OperandStack Class Reference
OperandStack Class Reference
#include <operand_stack.hpp>
Public Member Functions
pair< uint64_t, JVMType > pop ()
void push (uint64_t value, JVMType type)
void print ()
void insert (int index, uint64_t value, JVMType type)
pair< uint64_t, JVMType > readPosition (int position)
Private Attributes
vector< PrimitiveType * > operand_stack
Detailed Description
Definition at line 11 of file operand_stack.hpp.
Member Function Documentation
insert()
void OperandStack::insert (int index, uint64_t value, JVMType type)
Definition at line 27 of file operand_stack.cpp.
 {
   PrimitiveType *newValue = new PrimitiveType(value, type);
   operand_stack.push_back(newValue);
 }
References operand_stack.
Referenced by Instructions::DupX1::execute(), Instructions::DupX2::execute(), Instructions::Dup2X1::execute(), and Instructions::Dup2X2::execute().
pop()
pair< uint64_t, JVMType > OperandStack::pop ()
Definition at line 11 of file operand_stack.cpp.
{
   PrimitiveType* value = operand_stack.back();
   pair<uint64_t, JVMType> returnPair;
   returnPair.first = value->data;
   returnPair.second = value->type;
   operand_stack.pop_back();
   return returnPair;
 }
References PrimitiveType::data, operand_stack, and ComponentType::type.
Referenced by InvokeSimulation::exceptionInit(), Instructions::ArrayLength::execute(), Instructions::GetField::execute(), Instructions::PutField::execute(), Instructions::InterfaceAload::execute(), Instructions::InterfaceAstore::execute(), Instructions::Lcmp::execute(), Instructions::Fcmp::execute(), Instructions::Dcmp::execute(), Instructions::_Return::execute(), Instructions::AbstractStore::execute(), Instructions::ANewArray::execute(), Instructions::Athrow::execute(), Instructions::If::execute(), Instructions::If_icmp::execute(), Instructions::Ifnonnull::execute(), Instructions::Ifnull::execute(), Instructions::LookupSwitch::execute(), Instructions::MultiANewArray::execute(), Instructions::NewArray::execute(), Instructions::Pop::execute(), Instructions::Pop2::execute(), Instructions::PutStatic::execute(), Instructions::Swap::execute(), Instructions::TableSwitch::execute(), InvokeSimulation::getResultStringFromArgs(), Thread::initializeFrameVariableVector(), InvokeSimulation::println(), and InvokeSimulation::stringMethod().
print()
void OperandStack::print ()
Definition at line 4 of file operand_stack.cpp.
{
   std::cout << "PILHA" << endl;
   for(size_t i=0; i < this->operand_stack.size();i++){
     this->operand_stack[i]->print();
   }
   std::cout << "FIMPILHA" << endl;
 }
References operand_stack.
push()
void OperandStack::push (uint64_t value, JVMType type)
Definition at line 21 of file operand_stack.cpp.
 {
   PrimitiveType *newValue = new PrimitiveType(value, type);
   operand_stack.push_back(newValue);
 }
References operand_stack.
Referenced by Instructions::ArrayLength::execute(), Instructions::GetField::execute(), Instructions::New::execute(), Instructions::InterfaceAload::execute(), Instructions::Lcmp::execute(), Instructions::Fcmp::execute(), Instructions::Dcmp::execute(), Instructions::AconstNull::execute(), Instructions::Iconst::execute(), Instructions::Lconst::execute(), Instructions::Fconst::execute(), Instructions::Dconst::execute(), Instructions::AbstractLoad::execute(), Instructions::_Return::execute(), Instructions::ANewArray::execute(), Instructions::Dup::execute(), Instructions::Dup2::execute(), Instructions::GetStatic::execute(), Instructions::Jsr::execute(), Instructions::Ldc::execute(), Instructions::LdcW::execute(), Instructions::Ldc2W::execute(), Instructions::MultiANewArray::execute(), Instructions::NewArray::execute(), Instructions::Bipush::execute(), Instructions::Sipush::execute(), Instructions::Swap::execute(), Thread::handleException(), and InvokeSimulation::stringMethod().
readPosition()
pair< uint64_t, JVMType > OperandStack::readPosition (int position)
Definition at line 33 of file operand_stack.cpp.
 {
   int end = operand_stack.size()-1;
   pair<uint64_t, JVMType> positionValue(operand_stack[end-position]->data, operand_stack[end-position]->type);
   return positionValue;
 }
References operand_stack.
Referenced by Instructions::Dup::execute(), Instructions::DupX1::execute(), Instructions::DupX2::execute(), Instructions::Dup2::execute(), Instructions::Dup2X1::execute(), and Instructions::Dup2X2::execute().
Field Documentation
operand_stack
vector<PrimitiveType*> OperandStack::operand_stack private
Definition at line 13 of file operand_stack.hpp.
Referenced by insert(), pop(), print(), push(), and readPosition().
The documentation for this class was generated from the following files:
include/interpretador/operand_stack.hpp
src/interpretador/operand_stack.cpp