SB-2020-2-JVM: Instructions::Ldc Class Reference
Instructions::Ldc Class Reference
#include <ldc.hpp>
Public Member Functions
Ldc (Attribute::CodeAttribute *code_attr, uint8_t opcode)
int execute (Frame *frame)
string toString ()
Public Member Functions inherited from Instructions::BaseInstruction
BaseInstruction (Attribute::CodeAttribute *code_attr, uint8_t opcode)
virtual ~BaseInstruction ()
virtual void print ()
virtual void print (int)
Private Attributes
uint8_t param
Additional Inherited Members
Static Public Member Functions inherited from Instructions::BaseInstruction
static string getTypePrefix (uint8_t type)
static BaseInstruction * getInstance (Attribute::CodeAttribute *code_attr, uint8_t opcode, uint32_t pc)
Data Fields inherited from Instructions::BaseInstruction
uint8_t opcode
uint16_t pc
Protected Member Functions inherited from Instructions::BaseInstruction
string hexToString (int)
string intToString (int)
string intToSignedString (int)
string createStringWithCPRef (string name, uint16_t index)
string tabs (int)
Protected Attributes inherited from Instructions::BaseInstruction
Attribute::CodeAttribute * code_attr
Detailed Description
Definition at line 8 of file ldc.hpp.
Constructor & Destructor Documentation
Ldc()
Ldc::Ldc (Attribute::CodeAttribute * code_attr, uint8_t opcode)
Definition at line 6 of file ldc.cpp.
     :BaseInstruction(code_attr, opcode){
   FileReader *f_reader = this->code_attr->class_file->file_reader;
   f_reader->readBytes(1, this->param);
 }
References AttributeInfo::class_file, ClassFile::file_reader, param, and FileReader::readBytes().
Member Function Documentation
execute()
int Ldc::execute (Frame * frame) virtual
Reimplemented from Instructions::BaseInstruction.
Definition at line 12 of file ldc.cpp.
{
     CpInfo* cp_entry = this->code_attr->class_file->getConstantPoolEntry(this->param);
     switch (cp_entry->tag) {
         case 0x3:{
             CP::IntegerInfo* cp_integer = (CP::IntegerInfo *)cp_entry;
             frame->operand_stack.push(cp_integer->returnInteger(), Int);
             break;
         }
         case 0x4:{
             CP::FloatInfo* cp_float = (CP::FloatInfo *)cp_entry;
             float val = cp_float->returnFloat();
             frame->operand_stack.push(*(uint64_t*)&val, Float);
             break;
         }
         case 0x7:{ // Class_info
             string class_name = cp_entry->toString();
             int new_ref = ReferenceResolver::resolveClassName(class_name, frame->thread->method_area);
             frame->operand_stack.push(new_ref, Reference);
             break;
         }
         case 0x8:{ // String_info
             StringType* string_component = new StringType(cp_entry->toString());
             int heap_index = frame->thread->heap_ref->storeComponent(string_component);
             frame->operand_stack.push(heap_index, Reference);
             break;
         }
         case 0xf:{
             //CP::MethodHandleInfo* cp_class = (CP::MethodHandleInfo *)cp_entry;
             //MethodHandleType* method_handle_component = new MethodHandleType(JVMMethodHandle, cp_class);
             break;
         }
         case 0x10:{
             CP::MethodTypeInfo* cp_class = (CP::MethodTypeInfo *)cp_entry;
             StringType* string_component = new StringType(cp_class->toString());
             int heap_index = frame->thread->heap_ref->storeComponent(string_component);
             frame->operand_stack.push(heap_index, Reference);
             break;
         }
         default:{
             throw std::runtime_error("wrong LDC cpinfo tag");
         }
     }
     return frame->local_pc+=2;
 }
References AttributeInfo::class_file, Instructions::BaseInstruction::code_attr, Float, ClassFile::getConstantPoolEntry(), Thread::heap_ref, Int, Frame::local_pc, Thread::method_area, Frame::operand_stack, param, OperandStack::push(), Reference, ReferenceResolver::resolveClassName(), CP::FloatInfo::returnFloat(), CP::IntegerInfo::returnInteger(), Heap::storeComponent(), CpInfo::tag, Frame::thread, CP::MethodTypeInfo::toString(), and CpInfo::toString().
toString()
string Ldc::toString () virtual
Reimplemented from Instructions::BaseInstruction.
Definition at line 60 of file ldc.cpp.
                     {
   CpInfo* cp_val = this->code_attr->class_file->getConstantPoolEntry(this->param);
   stringstream paramString;
   paramString << (int)this->param;
   return "ldc #" + paramString.str() + " <" + cp_val->toString() + ">";
 }
References AttributeInfo::class_file, Instructions::BaseInstruction::code_attr, ClassFile::getConstantPoolEntry(), param, and CpInfo::toString().
Field Documentation
param
uint8_t Instructions::Ldc::param private
Definition at line 10 of file ldc.hpp.
Referenced by execute(), Ldc(), and toString().
The documentation for this class was generated from the following files:
include/attribute_info_classes/instruction_classes/ldc.hpp
src/attribute_info_classes/instruction_classes/ldc.cpp