SB-2020-2-JVM: Teste_java Class Reference
Teste_java Class Reference
Static Public Member Functions
static void main (String[] args)
Detailed Description
Author
gabriel
Definition at line 11 of file Teste_java.java.
Member Function Documentation
main()
static void Teste_java.main (String[] args) inline static
Parameters
args the command line arguments
Definition at line 16 of file Teste_java.java.
{
         Teste teste = new Teste();
         teste.setX(13);
         teste.setY(1);
         int valor = teste.difference();
         System.out.println(valor);
     }
References Teste.difference(), Abstract.setX(), and Abstract.setY().
The documentation for this class was generated from the following file:
tests/Teste_java.java