SB-2020-2-JVM: Instructions::InvokeVirtual Class Reference
Instructions::InvokeVirtual Class Reference
#include <invokevirtual.hpp>
Public Member Functions
InvokeVirtual (Attribute::CodeAttribute *code_attr, uint8_t opcode)
string toString ()
int execute (Frame *)
Public Member Functions inherited from Instructions::BaseInstruction
BaseInstruction (Attribute::CodeAttribute *code_attr, uint8_t opcode)
virtual ~BaseInstruction ()
virtual void print ()
virtual void print (int)
Private Attributes
uint16_t index
Additional Inherited Members
Static Public Member Functions inherited from Instructions::BaseInstruction
static string getTypePrefix (uint8_t type)
static BaseInstruction * getInstance (Attribute::CodeAttribute *code_attr, uint8_t opcode, uint32_t pc)
Data Fields inherited from Instructions::BaseInstruction
uint8_t opcode
uint16_t pc
Protected Member Functions inherited from Instructions::BaseInstruction
string hexToString (int)
string intToString (int)
string intToSignedString (int)
string createStringWithCPRef (string name, uint16_t index)
string tabs (int)
Protected Attributes inherited from Instructions::BaseInstruction
Attribute::CodeAttribute * code_attr
Detailed Description
Definition at line 8 of file invokevirtual.hpp.
Constructor & Destructor Documentation
InvokeVirtual()
InvokeVirtual::InvokeVirtual (Attribute::CodeAttribute * code_attr, uint8_t opcode)
Definition at line 9 of file invokevirtual.cpp.
     :BaseInstruction(code_attr, opcode){
   FileReader *f_reader = this->code_attr->class_file->file_reader;
   f_reader->readBytes(2, this->index);
 }
References AttributeInfo::class_file, ClassFile::file_reader, index, and FileReader::readBytes().
Member Function Documentation
execute()
int InvokeVirtual::execute (Frame * frame) virtual
Reimplemented from Instructions::BaseInstruction.
Definition at line 20 of file invokevirtual.cpp.
{
   CP::MethodRefInfo* ref_info = (CP::MethodRefInfo*)frame->current_method->class_file->getConstantPoolEntry(this->index);
   string symbolic_ref = ref_info->toString();
   string descriptor = ref_info->getDescriptor();
   pair<string,string> names = ReferenceResolver::separateSymbol(symbolic_ref, ".");
   if(symbolic_ref == "java/io/PrintStream.println"){
     InvokeSimulation::println(frame, this->index);
   }
   else if(names.first == "java/lang/StringBuilder"){
     InvokeSimulation::stringMethod(names.second, frame, this->index);
   }
   else{
     frame->thread->invokeInstanceMethod(names.first, names.second, descriptor);
   }
   frame->local_pc += 3;
   return frame->local_pc;
 }
References MethodInfo::class_file, Frame::current_method, ClassFile::getConstantPoolEntry(), CP::MethodRefInfo::getDescriptor(), index, Thread::invokeInstanceMethod(), Frame::local_pc, InvokeSimulation::println(), ReferenceResolver::separateSymbol(), InvokeSimulation::stringMethod(), Frame::thread, and CP::MethodRefInfo::toString().
toString()
string InvokeVirtual::toString () virtual
Reimplemented from Instructions::BaseInstruction.
Definition at line 15 of file invokevirtual.cpp.
{
   return this->createStringWithCPRef("invokevirtual", this->index);
 }
References Instructions::BaseInstruction::createStringWithCPRef(), and index.
Field Documentation
index
uint16_t Instructions::InvokeVirtual::index private
Definition at line 10 of file invokevirtual.hpp.
Referenced by execute(), InvokeVirtual(), and toString().
The documentation for this class was generated from the following files:
include/attribute_info_classes/instruction_classes/invokevirtual.hpp
src/attribute_info_classes/instruction_classes/invokevirtual.cpp