SB-2020-2-JVM: ExecutionEngine Class Reference
ExecutionEngine Class Reference
#include <execution_engine.hpp>
Public Member Functions
void start ()
void loadMethodArea (string intial_class_name)
Static Public Member Functions
static ExecutionEngine * getInstance ()
static void releaseInstance ()
Data Fields
Thread * main_thread
Private Member Functions
ExecutionEngine ()
~ExecutionEngine ()
Private Attributes
MethodArea * method_area
vector< Thread * > threads
Heap * heap
Static Private Attributes
static ExecutionEngine * instance = NULL
Detailed Description
Definition at line 8 of file execution_engine.hpp.
Constructor & Destructor Documentation
ExecutionEngine()
ExecutionEngine::ExecutionEngine () inline private
Definition at line 11 of file execution_engine.hpp.
 {};
Referenced by getInstance().
~ExecutionEngine()
ExecutionEngine::~ExecutionEngine () private
Definition at line 43 of file execution_engine.cpp.
{
   Heap::releaseInstance();
   MethodArea::realeaseInstance();
   this->heap = NULL;
   this->method_area = NULL;
   for(uint i=0;i<this->threads.size();i+=1){
     delete this->threads[i];
   }
   this->threads.clear();
 }
References heap, method_area, MethodArea::realeaseInstance(), Heap::releaseInstance(), and threads.
Member Function Documentation
getInstance()
ExecutionEngine * ExecutionEngine::getInstance () static
Definition at line 30 of file execution_engine.cpp.
{
   if(instance==NULL){
     ExecutionEngine::instance = new ExecutionEngine();
   }
   return ExecutionEngine::instance ;
 };
References ExecutionEngine(), and instance.
Referenced by InterfaceLoader::initializeInterface(), and main().
loadMethodArea()
void ExecutionEngine::loadMethodArea (string intial_class_name)
Definition at line 5 of file execution_engine.cpp.
{
   this->heap = Heap::getInstance();
   this->method_area = MethodArea::getInstance();
   ClassLoader::loadClass(load_class_name, this->method_area);
 }
References Heap::getInstance(), MethodArea::getInstance(), heap, ClassLoader::loadClass(), and method_area.
Referenced by main().
releaseInstance()
void ExecutionEngine::releaseInstance () static
Definition at line 36 of file execution_engine.cpp.
{
   if(ExecutionEngine::instance != NULL){
     delete ExecutionEngine::instance;
     ExecutionEngine::instance = NULL;
   }
 }
References instance.
Referenced by main().
start()
void ExecutionEngine::start ()
Definition at line 12 of file execution_engine.cpp.
{
   // A inicializacao da jvm consiste em:
   // Achar classe inicial (que tem a main nela)
   // Fazer Load, Link e Initalize dela
   // Rodar a main
   this->threads.push_back(
     new Thread(this->method_area)
   );
   this->main_thread = this->threads[0];
   string inital_class_name = this->method_area->getMainMethod()->class_file->getThisClassName();
   this->main_thread->runMain();
 }
References MethodInfo::class_file, MethodArea::getMainMethod(), ClassFile::getThisClassName(), main_thread, method_area, Thread::runMain(), and threads.
Referenced by main().
Field Documentation
heap
Heap* ExecutionEngine::heap private
Definition at line 16 of file execution_engine.hpp.
Referenced by loadMethodArea(), and ~ExecutionEngine().
instance
ExecutionEngine * ExecutionEngine::instance = NULL static private
Definition at line 10 of file execution_engine.hpp.
Referenced by getInstance(), and releaseInstance().
main_thread
Thread* ExecutionEngine::main_thread
Definition at line 19 of file execution_engine.hpp.
Referenced by InterfaceLoader::initializeInterface(), and start().
method_area
MethodArea* ExecutionEngine::method_area private
Definition at line 14 of file execution_engine.hpp.
Referenced by loadMethodArea(), start(), and ~ExecutionEngine().
threads
vector<Thread*> ExecutionEngine::threads private
Definition at line 15 of file execution_engine.hpp.
Referenced by start(), and ~ExecutionEngine().
The documentation for this class was generated from the following files:
include/interpretador/execution_engine.hpp
src/interpretador/execution_engine.cpp