SB-2020-2-JVM: Instructions::BaseInstruction Class Reference
Instructions::BaseInstruction Class Reference
#include <instruction.hpp>
Inherited by Instructions::ANewArray, Instructions::AbstractLoad, Instructions::AbstractStore, Instructions::AconstNull, Instructions::Add, Instructions::And, Instructions::ArrayLength, Instructions::Athrow, Instructions::Bipush, Instructions::CheckCast, Instructions::Dcmp, Instructions::Dconst, Instructions::Div, Instructions::Dup, Instructions::Dup2, Instructions::Dup2X1, Instructions::Dup2X2, Instructions::DupX1, Instructions::DupX2, Instructions::Fcmp, Instructions::Fconst, Instructions::GetField, Instructions::GetStatic, Instructions::Goto, Instructions::Goto_W, Instructions::Iconst, Instructions::If, Instructions::If_acmp, Instructions::If_icmp, Instructions::Ifnonnull, Instructions::Ifnull, Instructions::Inc, Instructions::Instanceof, Instructions::InterfaceAload, Instructions::InterfaceAstore, Instructions::InvokeInterface, Instructions::InvokeSpecial, Instructions::InvokeStatic, Instructions::InvokeVirtual, Instructions::Jsr, Instructions::Jsr_W, Instructions::Lcmp, Instructions::Lconst, Instructions::Ldc, Instructions::Ldc2W, Instructions::LdcW, Instructions::LookupSwitch, Instructions::MonitorEnter, Instructions::MonitorExit, Instructions::Mul, Instructions::MultiANewArray, Instructions::Neg, Instructions::New, Instructions::NewArray, Instructions::Nop, Instructions::Or, Instructions::Pop, Instructions::Pop2, Instructions::PutField, Instructions::PutStatic, Instructions::Rem, Instructions::Ret, Instructions::Return, Instructions::Shl, Instructions::Shr, Instructions::Sipush, Instructions::Sub, Instructions::Swap, Instructions::TableSwitch, Instructions::TypeConversion, Instructions::Ushr, Instructions::Wide, Instructions::Xor, and Instructions::_Return.
Public Member Functions
BaseInstruction (Attribute::CodeAttribute *code_attr, uint8_t opcode)
virtual ~BaseInstruction ()
virtual void print ()
virtual void print (int)
virtual string toString ()
virtual int execute (Frame *frame)
Static Public Member Functions
static string getTypePrefix (uint8_t type)
static BaseInstruction * getInstance (Attribute::CodeAttribute *code_attr, uint8_t opcode, uint32_t pc)
Data Fields
uint8_t opcode
uint16_t pc
Protected Member Functions
string hexToString (int)
string intToString (int)
string intToSignedString (int)
string createStringWithCPRef (string name, uint16_t index)
string tabs (int)
Protected Attributes
Attribute::CodeAttribute * code_attr
Detailed Description
Definition at line 37 of file instruction.hpp.
Constructor & Destructor Documentation
BaseInstruction()
BaseInstruction::BaseInstruction (Attribute::CodeAttribute * code_attr, uint8_t opcode)
Definition at line 7 of file instruction.cpp.
{
   this->code_attr = code_attr;
   this->opcode = opcode;
 }
References code_attr, and opcode.
Referenced by getInstance().
~BaseInstruction()
virtual Instructions::BaseInstruction::~BaseInstruction () inline virtual
Definition at line 49 of file instruction.hpp.
 {};
Member Function Documentation
createStringWithCPRef()
string BaseInstruction::createStringWithCPRef (string name, uint16_t index) protected
Definition at line 64 of file instruction.cpp.
{
   return name +" #" + this->intToString(index) +
   " <" + this->code_attr->class_file->getConstantPoolEntry(index)->toString()
   + ">";
 }
References AttributeInfo::class_file, code_attr, ClassFile::getConstantPoolEntry(), intToString(), and CpInfo::toString().
Referenced by Instructions::ANewArray::toString(), Instructions::CheckCast::toString(), Instructions::GetField::toString(), Instructions::Instanceof::toString(), Instructions::InvokeInterface::toString(), Instructions::InvokeSpecial::toString(), Instructions::InvokeStatic::toString(), Instructions::InvokeVirtual::toString(), Instructions::MultiANewArray::toString(), Instructions::New::toString(), and Instructions::PutField::toString().
execute()
int BaseInstruction::execute (Frame * frame) virtual
Reimplemented in Instructions::TableSwitch, Instructions::Swap, Instructions::PutStatic, Instructions::Sipush, Instructions::Bipush, Instructions::Pop2, Instructions::Pop, Instructions::Nop, Instructions::NewArray, Instructions::MultiANewArray, Instructions::LookupSwitch, Instructions::Ldc2W, Instructions::LdcW, Instructions::Ldc, Instructions::Jsr, Instructions::InvokeSpecial, Instructions::Ifnull, Instructions::Ifnonnull, Instructions::If_acmp, Instructions::If_icmp, Instructions::If, Instructions::Goto_W, Instructions::Goto, Instructions::GetStatic, Instructions::Dup2X2, Instructions::Dup2X1, Instructions::Dup2, Instructions::DupX2, Instructions::DupX1, Instructions::Dup, Instructions::Athrow, Instructions::ANewArray, Instructions::AbstractStore, Instructions::_Return, Instructions::AbstractLoad, Instructions::Dconst, Instructions::Fconst, Instructions::Lconst, Instructions::Iconst, Instructions::AconstNull, Instructions::Dcmp, Instructions::Fcmp, Instructions::Lcmp, Instructions::InterfaceAstore, Instructions::InterfaceAload, Instructions::Return, Instructions::PutField, Instructions::New, Instructions::InvokeVirtual, Instructions::InvokeStatic, Instructions::Inc, Instructions::GetField, Instructions::ArrayLength, Instructions::Xor, Instructions::Ushr, Instructions::Sub, Instructions::Shr, Instructions::Shl, Instructions::Rem, Instructions::Or, Instructions::Neg, Instructions::Mul, Instructions::Div, Instructions::And, Instructions::Add, and Instructions::TypeConversion.
Definition at line 12 of file instruction.cpp.
{
   this->print();
   return frame->local_pc++;
 }
References Frame::local_pc, and print().
Referenced by Frame::runInstruction().
getInstance()
BaseInstruction * BaseInstruction::getInstance (Attribute::CodeAttribute * code_attr, uint8_t opcode, uint32_t pc) static
Definition at line 87 of file instruction.cpp.
{
   switch (opcode){
   case 0x0:
     return new Nop(code_attr, opcode);
   case 0x1:
     return new AconstNull(code_attr, opcode);
   case 0x2 ... 0x8:
     return new Iconst(code_attr, opcode);
   case 0x9 ... 0xa:
     return new Lconst(code_attr, opcode);
   case 0xb ... 0xd:
     return new Fconst(code_attr, opcode);
   case 0xe ... 0xf:
     return new Dconst(code_attr, opcode);
   case 0x10:
     return new Bipush(code_attr, opcode);
   case 0x11:
     return new Sipush(code_attr, opcode);
   case 0x12:
     return new Ldc(code_attr, opcode);
   case 0x13:
     return new LdcW(code_attr, opcode);
   case 0x14:
     return new Ldc2W(code_attr, opcode);
   case 0x15:
     return new Iload(code_attr, opcode);
   case 0x16:
     return new Lload(code_attr, opcode);
   case 0x17:
     return new Fload(code_attr, opcode);
   case 0x18:
     return new Dload(code_attr, opcode);
   case 0x19:
     return new Aload(code_attr, opcode);
   case 0x1a ... 0x1d:
     return new Iload(code_attr, opcode);
   case 0x1e ... 0x21:
     return new Lload(code_attr, opcode);
   case 0x22 ... 0x25:
     return new Fload(code_attr, opcode);
   case 0x26 ... 0x29:
     return new Dload(code_attr, opcode);
   case 0x2a ... 0x2d:
     return new Aload(code_attr, opcode);
   case 0x2e:
     return new Iaload(code_attr, opcode);
   case 0x2f:
     return new Laload(code_attr, opcode);
   case 0x30:
     return new Faload(code_attr, opcode);
   case 0x31:
     return new Baload(code_attr, opcode);
   case 0x32:
     return new Aaload(code_attr, opcode);
   case 0x33:
     return new Baload(code_attr, opcode);
   case 0x34:
     return new Caload(code_attr, opcode);
   case 0x35:
     return new Saload(code_attr, opcode);
   case 0x36:
     return new Istore(code_attr, opcode);
   case 0x37:
     return new Lstore(code_attr, opcode);
   case 0x38:
     return new Fstore(code_attr, opcode);
   case 0x39:
     return new Dstore(code_attr, opcode);
   case 0x3a:
     return new Astore(code_attr, opcode);
   case 0x3b ... 0x3e:
     return new Istore(code_attr, opcode);
   case 0x3f ... 0x42:
     return new Lstore(code_attr, opcode);
   case 0x43 ... 0x46:
     return new Fstore(code_attr, opcode);
   case 0x47 ... 0x4a:
     return new Dstore(code_attr, opcode);
   case 0x4b ... 0x4e:
     return new Astore(code_attr, opcode);
   case 0x4f:
     return new Iastore(code_attr, opcode);
   case 0x50:
     return new Lastore(code_attr, opcode);
   case 0x51:
     return new Fastore(code_attr, opcode);
   case 0x52:
     return new Dastore(code_attr, opcode);
   case 0x53:
     return new Aastore(code_attr, opcode);
   case 0x54:
     return new Bastore(code_attr, opcode);
   case 0x55:
     return new Castore(code_attr, opcode);
   case 0x56:
     return new Sastore(code_attr, opcode);
   case 0x57:
     return new Pop(code_attr, opcode);
   case 0x58:
     return new Pop2(code_attr, opcode);
   case 0x59:
     return new Dup(code_attr, opcode);
   case 0x5a:
     return new DupX1(code_attr, opcode);
   case 0x5b:
     return new DupX2(code_attr, opcode);
   case 0x5c:
     return new Dup2(code_attr, opcode);
   case 0x5d:
     return new Dup2X1(code_attr, opcode);
   case 0x5e:
     return new Dup2X2(code_attr, opcode);
   case 0x5f:
     return new Swap(code_attr, opcode);
   case 0x60 ... 0x63:
     return new Add(code_attr, opcode);
   case 0x64 ... 0x67:
     return new Sub(code_attr, opcode);
   case 0x68 ... 0x6b:
     return new Mul(code_attr, opcode);
   case 0x6c ... 0x6f:
     return new Div(code_attr, opcode);
   case 0x70 ... 0x73:
     return new Rem(code_attr, opcode);
   case 0x74 ... 0x77:
     return new Neg(code_attr, opcode);
   case 0x78 ... 0x79:
     return new Shl(code_attr, opcode);
   case 0x7a ... 0x7b:
     return new Shr(code_attr, opcode);
   case 0x7c ... 0x7d:
     return new Ushr(code_attr, opcode);
   case 0x7e ... 0x7f:
     return new And(code_attr, opcode);
   case 0x80 ... 0x81:
     return new Or(code_attr, opcode);
   case 0x82 ... 0x83:
     return new Xor(code_attr, opcode);
   case 0x84:
     return new Inc(code_attr, opcode);
   case 0x85 ... 0x93:
     return new TypeConversion(code_attr, opcode);
   case 0x94:
     return new Lcmp(code_attr, opcode);
   case 0x95 ... 0x96:
     return new Fcmp(code_attr, opcode);
   case 0x97 ... 0x98:
     return new Dcmp(code_attr, opcode);
   case 0x99 ... 0x9e:
     return new If(code_attr, opcode);
   case 0x9f ... 0xa4:
     return new If_icmp(code_attr, opcode);
   // case 0xa5 ... 0xa6:
     // return new If_acmp(code_attr, opcode);
   case 0xa7:
     return new Goto(code_attr, opcode);
   case 0xa8:
     return new Jsr(code_attr, opcode);
   case 0xa9:
     return new Ret(code_attr, opcode);
   case 0xaa:
     return new TableSwitch(code_attr, opcode, pc);
   case 0xab:
     return new LookupSwitch(code_attr, opcode, pc);
   case 0xac ... 0xb0:
     return new _Return(code_attr, opcode);
   case 0xb1:
     return new Return(code_attr, opcode);
   case 0xb2:
     return new GetStatic(code_attr, opcode);
   case 0xb3:
     return new PutStatic(code_attr, opcode);
   case 0xb4:
     return new GetField(code_attr, opcode);
   case 0xb5:
     return new PutField(code_attr, opcode);
   case 0xb6:
     return new InvokeVirtual(code_attr, opcode);
   case 0xb7:
     return new InvokeSpecial(code_attr, opcode);
   case 0xb8:
     return new InvokeStatic(code_attr, opcode);
   case 0xb9: // nao foi testado
     return new InvokeInterface(code_attr, opcode);
   case 0xbb:
     return new New(code_attr, opcode);
   case 0xbc:
     return new NewArray(code_attr, opcode);
   case 0xbd:
     return new ANewArray(code_attr, opcode);
   case 0xbe:
     return new ArrayLength(code_attr, opcode);
   case 0xbf:
     return new Athrow(code_attr, opcode);
   case 0xc0:
     return new CheckCast(code_attr, opcode);
   case 0xc1:
     return new Instanceof(code_attr, opcode);
   case 0xc2:
     return new MonitorEnter(code_attr, opcode);
   case 0xc3:
     return new MonitorExit(code_attr, opcode);
   case 0xc4: // nao foi testado
     return new Wide(code_attr, opcode);
   case 0xc5: // nao foi testado
     return new MultiANewArray(code_attr, opcode);
   case 0xc6: // nao foi testado
     return new Ifnull(code_attr, opcode);
   case 0xc7: // nao foi testado
     return new Ifnonnull(code_attr, opcode);
   case 0xc8: // nao foi testado
     return new Goto_W(code_attr, opcode);
   case 0xc9: // nao foi testado
     return new Jsr_W(code_attr, opcode);
   }
   return new BaseInstruction(code_attr, opcode);
 }
References BaseInstruction(), code_attr, opcode, and pc.
Referenced by Attribute::CodeAttribute::loadInstructions(), and Instructions::Wide::Wide().
getTypePrefix()
string BaseInstruction::getTypePrefix (uint8_t type) static
Definition at line 70 of file instruction.cpp.
{
   switch (type){
     case I_TYPE :
       return "i";
     case F_TYPE:
       return "f";
     case L_TYPE:
       return "l";
     case D_TYPE:
       return "d";
     case A_TYPE:
       return "a";
     default:
       return "undefinedPrefix";
   }
 }
References A_TYPE, D_TYPE, F_TYPE, I_TYPE, and L_TYPE.
Referenced by Instructions::Add::toString(), Instructions::And::toString(), Instructions::Div::toString(), Instructions::Mul::toString(), Instructions::Neg::toString(), Instructions::Or::toString(), Instructions::Rem::toString(), Instructions::_Return::toString(), Instructions::Shl::toString(), Instructions::Shr::toString(), Instructions::Sub::toString(), Instructions::Ushr::toString(), Instructions::Xor::toString(), and Instructions::Inc::toString().
hexToString()
string BaseInstruction::hexToString (int param) protected
Definition at line 32 of file instruction.cpp.
{
   stringstream paramString;
   paramString << hex << param;
   return paramString.str();
 }
Referenced by toString(), Instructions::AbstractLoad::toString(), and Instructions::AbstractStore::toString().
intToSignedString()
string BaseInstruction::intToSignedString (int) protected
Definition at line 51 of file instruction.cpp.
{
   string signalStr = "+";
   if(param < 0){
     param *=1;
     signalStr = "-";
   }
   stringstream paramString;
   paramString << param;
   return signalStr + paramString.str();
 }
Referenced by Instructions::LookupSwitch::print(), Instructions::TableSwitch::print(), Instructions::Goto_W::toString(), Instructions::Ifnonnull::toString(), Instructions::Ifnull::toString(), and Instructions::Jsr_W::toString().
intToString()
string BaseInstruction::intToString (int param) protected
Definition at line 38 of file instruction.cpp.
{
   stringstream paramString;
   paramString << param;
   return paramString.str();
 }
Referenced by createStringWithCPRef(), Instructions::LookupSwitch::print(), Instructions::TableSwitch::print(), Instructions::Wide::print(), Instructions::Lconst::toString(), Instructions::Fconst::toString(), Instructions::Dconst::toString(), Instructions::GetStatic::toString(), Instructions::Goto::toString(), Instructions::Goto_W::toString(), Instructions::If::toString(), Instructions::If_icmp::toString(), Instructions::Ifnonnull::toString(), Instructions::Ifnull::toString(), Instructions::Inc::toString(), Instructions::InvokeInterface::toString(), Instructions::Jsr::toString(), Instructions::Jsr_W::toString(), Instructions::MultiANewArray::toString(), Instructions::NewArray::toString(), Instructions::PutStatic::toString(), and Instructions::Ret::toString().
print() [1/2]
void BaseInstruction::print () virtual
Definition at line 24 of file instruction.cpp.
{
   cout << dec << this->toString() << endl;
 }
References toString().
Referenced by execute(), print(), and Attribute::CodeAttribute::printInfo().
print() [2/2]
void BaseInstruction::print (int n_tabs) virtual
Reimplemented in Instructions::Wide, Instructions::TableSwitch, and Instructions::LookupSwitch.
Definition at line 28 of file instruction.cpp.
{
   this->print();
 }
References print().
tabs()
string BaseInstruction::tabs (int n_tabs) protected
Definition at line 44 of file instruction.cpp.
{
   string str= "";
   while(n_tabs--)str+= "\t";
   return str;
 }
Referenced by Instructions::LookupSwitch::print(), and Instructions::TableSwitch::print().
toString()
string BaseInstruction::toString () virtual
Reimplemented in Instructions::Swap, Instructions::Return, Instructions::Ret, Instructions::PutStatic, Instructions::PutField, Instructions::Sipush, Instructions::Bipush, Instructions::Pop2, Instructions::Pop, Instructions::Nop, Instructions::NewArray, Instructions::New, Instructions::MultiANewArray, Instructions::MonitorExit, Instructions::MonitorEnter, Instructions::Ldc2W, Instructions::LdcW, Instructions::Ldc, Instructions::Jsr_W, Instructions::Jsr, Instructions::InvokeVirtual, Instructions::InvokeStatic, Instructions::InvokeSpecial, Instructions::InvokeInterface, Instructions::Instanceof, Instructions::Inc, Instructions::Ifnull, Instructions::Ifnonnull, Instructions::If_acmp, Instructions::If_icmp, Instructions::If, Instructions::Goto_W, Instructions::Goto, Instructions::GetStatic, Instructions::GetField, Instructions::Dup2X2, Instructions::Dup2X1, Instructions::Dup2, Instructions::DupX2, Instructions::DupX1, Instructions::Dup, Instructions::CheckCast, Instructions::Athrow, Instructions::ArrayLength, Instructions::ANewArray, Instructions::Xor, Instructions::Ushr, Instructions::Sub, Instructions::AbstractStore, Instructions::Shr, Instructions::Shl, Instructions::_Return, Instructions::Rem, Instructions::Or, Instructions::Neg, Instructions::Mul, Instructions::AbstractLoad, Instructions::Div, Instructions::Dconst, Instructions::Fconst, Instructions::Lconst, Instructions::Iconst, Instructions::AconstNull, Instructions::Dcmp, Instructions::Fcmp, Instructions::Lcmp, Instructions::Sastore, Instructions::Castore, Instructions::Bastore, Instructions::Aastore, Instructions::Dastore, Instructions::Fastore, Instructions::Lastore, Instructions::Iastore, Instructions::And, Instructions::Saload, Instructions::Caload, Instructions::Baload, Instructions::Aaload, Instructions::Daload, Instructions::Faload, Instructions::Laload, Instructions::Iaload, Instructions::Add, and Instructions::TypeConversion.
Definition at line 17 of file instruction.cpp.
{
   string baseName  = "Instrucao Base (0x";
   baseName += this->hexToString(this->opcode);
   baseName += ")";
   return baseName ;
 }
References hexToString(), and opcode.
Referenced by print(), and Instructions::Wide::print().
Field Documentation
code_attr
Attribute::CodeAttribute* Instructions::BaseInstruction::code_attr protected
Definition at line 39 of file instruction.hpp.
Referenced by BaseInstruction(), Instructions::Bipush::Bipush(), createStringWithCPRef(), Instructions::ANewArray::execute(), Instructions::Ldc::execute(), Instructions::LdcW::execute(), Instructions::Ldc2W::execute(), Instructions::MultiANewArray::execute(), getInstance(), Instructions::Wide::print(), Instructions::Sipush::Sipush(), Instructions::GetStatic::toString(), Instructions::Ldc::toString(), Instructions::LdcW::toString(), Instructions::Ldc2W::toString(), and Instructions::PutStatic::toString().
opcode
uint8_t Instructions::BaseInstruction::opcode
Definition at line 46 of file instruction.hpp.
Referenced by BaseInstruction(), Instructions::Iconst::execute(), Instructions::Lconst::execute(), Instructions::Fconst::execute(), Instructions::Dconst::execute(), getInstance(), toString(), Instructions::Iconst::toString(), Instructions::Lconst::toString(), Instructions::Fconst::toString(), and Instructions::Dconst::toString().
pc
uint16_t Instructions::BaseInstruction::pc
Definition at line 47 of file instruction.hpp.
Referenced by getInstance(), Attribute::CodeAttribute::loadInstructions(), Instructions::LookupSwitch::LookupSwitch(), Instructions::LookupSwitch::print(), Instructions::TableSwitch::print(), Attribute::CodeAttribute::printInfo(), Instructions::TableSwitch::TableSwitch(), Instructions::Goto::toString(), Instructions::Goto_W::toString(), Instructions::If::toString(), Instructions::If_icmp::toString(), Instructions::Ifnonnull::toString(), Instructions::Ifnull::toString(), and Instructions::Jsr_W::toString().
The documentation for this class was generated from the following files:
include/attribute_info_classes/code_attribute_classes/instruction.hpp
src/attribute_info_classes/code_attribute_classes/instruction.cpp