SB-2020-2-JVM: FieldInfo Class Reference
FieldInfo Class Reference
#include <field_info.hpp>
Public Member Functions
FieldInfo (ClassFile *class_file)
~FieldInfo ()
string getName ()
string getDescriptor ()
bool isStatic ()
void printInfo ()
Private Attributes
uint16_t access_flags
uint16_t name_index
uint16_t descriptor_index
uint16_t attributes_count
vector< AttributeInfo * > attributes
ClassFile * class_file
Detailed Description
Definition at line 12 of file field_info.hpp.
Constructor & Destructor Documentation
FieldInfo()
FieldInfo::FieldInfo (ClassFile * class_file)
Definition at line 3 of file field_info.cpp.
{
   this->class_file = class_file;
   this->class_file->file_reader->readBytes(2, this->access_flags);
   this->class_file->file_reader->readBytes(2, this->name_index);
   this->class_file->file_reader->readBytes(2, this->descriptor_index);
   this->class_file->file_reader->readBytes(2, this->attributes_count);
   AttributeInfo::loadAttributes(this->attributes, this->attributes_count, this->class_file);
 }
References access_flags, attributes, attributes_count, class_file, descriptor_index, ClassFile::file_reader, AttributeInfo::loadAttributes(), name_index, and FileReader::readBytes().
~FieldInfo()
FieldInfo::~FieldInfo ()
Definition at line 12 of file field_info.cpp.
                       {
   this->class_file->deleteVector(this->attributes);
 }
References attributes, class_file, and ClassFile::deleteVector().
Member Function Documentation
getDescriptor()
string FieldInfo::getDescriptor ()
Definition at line 30 of file field_info.cpp.
{
   return this->class_file->getConstantPoolEntry(this->descriptor_index)->toString();
 }
References class_file, descriptor_index, ClassFile::getConstantPoolEntry(), and CpInfo::toString().
Referenced by JVMField::JVMField().
getName()
string FieldInfo::getName ()
Definition at line 26 of file field_info.cpp.
{
   return this->class_file->getConstantPoolEntry(this->name_index)->toString();
 }
References class_file, ClassFile::getConstantPoolEntry(), name_index, and CpInfo::toString().
Referenced by JVMField::JVMField().
isStatic()
bool FieldInfo::isStatic ()
Definition at line 34 of file field_info.cpp.
{
   if(this->class_file->beautifiedAccessFlags(this->access_flags, true, false)
     .find("static") != string::npos
   )
     return true;
   else return false;
 }
References ClassFile::beautifiedAccessFlags(), and class_file.
Referenced by JVMClass::initializeFields(), and JVMObject::initializeFields().
printInfo()
void FieldInfo::printInfo ()
Definition at line 16 of file field_info.cpp.
{
   cout << "\tName:              cpinfo #" << this->name_index << " <";
   cout << this->class_file->getConstantPoolEntry(this->name_index)->toString() << ">" << endl;
   cout << "\tDescriptor:        cpinfo #" << this->descriptor_index << " <";
   cout << this->class_file->getConstantPoolEntry(this->descriptor_index)->toString() << ">" << endl;
   cout << "\tAccess flags:      0x" <<  hex << this->access_flags << " " << this->class_file->beautifiedAccessFlags(this->access_flags, true, false) << endl;
   AttributeInfo::printAttributes(this->attributes, 2);
 }
References access_flags, attributes, ClassFile::beautifiedAccessFlags(), class_file, descriptor_index, ClassFile::getConstantPoolEntry(), name_index, AttributeInfo::printAttributes(), and CpInfo::toString().
Field Documentation
access_flags
uint16_t FieldInfo::access_flags private
Definition at line 14 of file field_info.hpp.
Referenced by FieldInfo(), and printInfo().
attributes
vector<AttributeInfo*> FieldInfo::attributes private
Definition at line 18 of file field_info.hpp.
Referenced by FieldInfo(), printInfo(), and ~FieldInfo().
attributes_count
uint16_t FieldInfo::attributes_count private
Definition at line 17 of file field_info.hpp.
Referenced by FieldInfo().
class_file
ClassFile* FieldInfo::class_file private
Definition at line 19 of file field_info.hpp.
Referenced by FieldInfo(), getDescriptor(), getName(), isStatic(), printInfo(), and ~FieldInfo().
descriptor_index
uint16_t FieldInfo::descriptor_index private
Definition at line 16 of file field_info.hpp.
Referenced by FieldInfo(), getDescriptor(), and printInfo().
name_index
uint16_t FieldInfo::name_index private
Definition at line 15 of file field_info.hpp.
Referenced by FieldInfo(), getName(), and printInfo().
The documentation for this class was generated from the following files:
include/field_info.hpp
src/field_info.cpp