SB-2020-2-JVM: ComponentType Class Reference
ComponentType Class Reference
#include <component_type.hpp>
Public Member Functions
ComponentType (JVMType component_type)
void setReference (int)
int getReference ()
virtual void print ()
virtual string toString ()
virtual ~ComponentType ()
Static Public Member Functions
static ComponentType * getDefaultValue (JVMType)
static JVMType getTypeFromDescriptor (string descriptor)
Data Fields
JVMType type
Protected Attributes
int heap_reference
Detailed Description
Definition at line 17 of file component_type.hpp.
Constructor & Destructor Documentation
ComponentType()
ComponentType::ComponentType (JVMType component_type)
Definition at line 7 of file component_type.cpp.
{
   this->type = component_type;
   this->heap_reference = -1;
   this->heap_reference = Heap::getInstance()->storeComponent(this);
 }
References Heap::getInstance(), heap_reference, Heap::storeComponent(), and type.
~ComponentType()
virtual ComponentType::~ComponentType () inline virtual
Definition at line 32 of file component_type.hpp.
 {};
Member Function Documentation
getDefaultValue()
ComponentType * ComponentType::getDefaultValue (JVMType type) static
Definition at line 13 of file component_type.cpp.
{
   if(type <= Reference){
     return new PrimitiveType(0, type);
   }
   if(type == JVMString) return new StringType( "");
   throw std::runtime_error("creating component type without default value");
 }
References JVMString, Reference, and type.
Referenced by ReferenceResolver::allocateArray(), ArrayType::initialize(), JVMField::JVMField(), and ReferenceResolver::resolveObjectByDescriptor().
getReference()
int ComponentType::getReference ()
Definition at line 35 of file component_type.cpp.
{
   return this->heap_reference;
 }
References heap_reference.
Referenced by Heap::createPrimitiveTypeArray(), and Heap::storeComponent().
getTypeFromDescriptor()
JVMType ComponentType::getTypeFromDescriptor (string descriptor) static
Definition at line 23 of file component_type.cpp.
{
   if(descriptor == "I") return Int;
   if(descriptor == "D") return Double;
   if(descriptor == "F") return Float;
   if(descriptor == "J") return Long;
   if(descriptor == "B") return Byte;
   if(descriptor[0] == 'L') return Reference;
   if(descriptor[0] == '[') return Reference;
   throw std::runtime_error("TypeError: descritor (" +descriptor +") nao possui tipo implementado");
 }
References Byte, Double, Float, Int, Long, and Reference.
Referenced by ReferenceResolver::allocateArray(), JVMField::JVMField(), and ReferenceResolver::resolveObjectByDescriptor().
print()
void ComponentType::print () virtual
Reimplemented in PrimitiveType, and ArrayType.
Definition at line 43 of file component_type.cpp.
{
   std::cout << "ComponentType" << endl;
 }
setReference()
void ComponentType::setReference (int i)
Definition at line 39 of file component_type.cpp.
{
   this->heap_reference = i;
 }
References heap_reference.
Referenced by Heap::storeComponent().
toString()
string ComponentType::toString () virtual
Reimplemented in StringType, PrimitiveType, JVMInterface, JVMField, JVMClass, ExceptionType, and ArrayType.
Definition at line 47 of file component_type.cpp.
{
   return "ComponentType";
 }
Referenced by InvokeSimulation::exceptionInit(), InvokeSimulation::getResultStringFromArgs(), ArrayType::print(), InvokeSimulation::println(), and InvokeSimulation::stringMethod().
Field Documentation
heap_reference
int ComponentType::heap_reference protected
Definition at line 19 of file component_type.hpp.
Referenced by ComponentType(), getReference(), and setReference().
type
JVMType ComponentType::type
Definition at line 21 of file component_type.hpp.
Referenced by ComponentType(), Instructions::GetField::execute(), Instructions::InterfaceAload::execute(), Instructions::GetStatic::execute(), getDefaultValue(), ArrayType::getIndexAsAsPrimitiveType(), JVMField::JVMField(), OperandStack::pop(), ArrayType::print(), PrimitiveType::print(), JVMField::setData(), ArrayType::setIndexAsPrimitiveType(), and PrimitiveType::toString().
The documentation for this class was generated from the following files:
include/interpretador/types/component_type.hpp
src/interpretador/types/component_type.cpp