SB-2020-2-JVM: Belote Class Reference
Belote Class Reference
Public Member Functions
Belote ()
Static Public Member Functions
static String retornaNome (int naipe)
static void printStatus ()
static void shuffle (Carta[] baralho)
static void main (String[] args)
Static Private Attributes
static Jogador[] jogadores
static Carta[] baralho
Detailed Description
Definition at line 4 of file Belote.java.
Constructor & Destructor Documentation
Belote()
Belote.Belote () inline
Definition at line 38 of file Belote.java.
                    {
         String[] nomes = {"Adam","Bob","Charlie","Daniel"};
         String[] cartaValores = {"As","Dois","Tres","Quatro","Cinco","Seis","Sete","Oito",
             "Nove","Dez","Valete","Dama","Rei"};
         jogadores = new Jogador[4];
         baralho = new Carta[4*13];
         for(int i=0;i<4;i++){
             jogadores[i] = new Jogador(nomes[i]);
             System.out.println(jogadores[i].nome);
         }
         for( int i=0;i<4;i++){
             for(int j=0;j<13;j++){
                 baralho[i*13+j] = new Carta(i,cartaValores[j],j+1);
                 System.out.println(baralho[i].nome);
             }
         }
         Belote.shuffle(baralho);
         for(int i = 0;i<4;i++){
             for(int j=0;j<13;j++)
             jogadores[i].addCarta(baralho[i*13+j]);
         }
     }
References baralho, jogadores, and shuffle().
Referenced by main().
Member Function Documentation
main()
static void Belote.main (String[] args) inline static
Definition at line 74 of file Belote.java.
{
         Belote jogo = new Belote();
         Belote.printStatus();
         int i,j,provavelGanhador;
         Carta mesa[] = new Carta[4];
         for(int k=0;k<4;k++){
             mesa[k] = new Carta(1,"1",1);
         }
         j=0;
         mesa[j] = jogadores[j].primeiroJogador();
         while(mesa[j]!=null){
             provavelGanhador=j;
             for(i=0;i<4;i++){
                 if(i!=j){
                     mesa[i] = jogadores[i].play(mesa[j].naipe);
                     if(mesa[i].valor > mesa[provavelGanhador].valor &&
                         mesa[i].naipe == mesa[provavelGanhador].naipe){
                         provavelGanhador=i;
                     }
                 }
             }
             System.out.println(jogadores[j].nome);
             System.out.println(" comecou jogando\n");
             System.out.println("As cartas jogadas foram: ");
             for(i=0;i<4;i++){
                 System.out.println(jogadores[i].nome);
                 System.out.println(" jogou ");
                 System.out.println(mesa[i].nome);
                 System.out.println(" de ");
                 Belote.retornaNome(mesa[i].naipe);
             }
             jogadores[provavelGanhador].ganheiRodada(mesa);
             j = provavelGanhador;
             System.out.println("\n\n");
             System.out.println(jogadores[j].nome);
             System.out.println(" Ganhou a rodada\n\n");
             mesa[j] = Belote.jogadores[j].primeiroJogador();
         }
         System.out.println("Pontuacao dos jogadores.\n");
         System.out.println(jogadores[0].nome);
         System.out.println( " =  ");
         System.out.println(jogadores[0].pontuacao);
         System.out.println(jogadores[1].nome);
         System.out.println( " =  ");
         System.out.println(jogadores[1].pontuacao);
         System.out.println(jogadores[2].nome);
         System.out.println( " =  ");
         System.out.println(jogadores[2].pontuacao);
         System.out.println(jogadores[3].nome);
         System.out.println( " =  ");
         System.out.println(jogadores[3].pontuacao);
     }
References Belote(), Jogador.ganheiRodada(), jogadores, Jogador.play(), Jogador.primeiroJogador(), printStatus(), and retornaNome().
printStatus()
static void Belote.printStatus () inline static
Definition at line 23 of file Belote.java.
{
         for(int i=0;i<4;i++){
             System.out.println("\nCartas de ");
             System.out.println(jogadores[i].nome);
             System.out.println("\n");
             for(int j=0;j<13;j++){
                 System.out.println(jogadores[i].cartas[j].nome);
                 System.out.println(" de ");
                 System.out.println(Belote.retornaNome(jogadores[i].cartas[j].naipe));
             }
         }
         System.out.println("\n");
         return;
     }
References Jogador.cartas, jogadores, Carta.naipe, and retornaNome().
Referenced by main().
retornaNome()
static String Belote.retornaNome (int naipe) inline static
Definition at line 8 of file Belote.java.
{
         if(naipe==0){
             return("Paus");
         }
         else if(naipe==1){
             return("Ouros");
         }
         else if(naipe==2){
             return("Copas");
         }
         else if(naipe==3){
             return("Espadas");
         }
         return(null);
     }
Referenced by main(), and printStatus().
shuffle()
static void Belote.shuffle (Carta[] baralho) inline static
Definition at line 64 of file Belote.java.
{
         int j;
         Carta swap = new Carta(1,"1",1);
         for(int i=0;i<52;i++){
             j = (int)(51);
             swap = baralho[i];
             baralho[i] = baralho[j];
             baralho[j] = swap;
         }
     }
References baralho.
Referenced by Belote().
Field Documentation
baralho
Carta [] Belote.baralho static private
Definition at line 6 of file Belote.java.
Referenced by Belote(), and shuffle().
jogadores
Jogador [] Belote.jogadores static private
Definition at line 5 of file Belote.java.
Referenced by Belote(), main(), and printStatus().
The documentation for this class was generated from the following file:
tests/Belote.java