SB-2020-2-JVM: MethodArea Class Reference
MethodArea Class Reference
#include <method_area.hpp>
Public Member Functions
ClassFile * insertNewClass (string class_name)
MethodInfo * getMainMethod ()
MethodInfo * getMethodByName (string class_name, string methodName, string args_descriptor)
ClassFile * getClassFile (string class_name)
bool isAlreadyIncluded (string class_name)
bool classHasMethod (string class_name, string method_name, string args_descriptor)
Static Public Member Functions
static MethodArea * getInstance ()
static void realeaseInstance ()
Private Member Functions
void searchMainMethod (ClassFile *)
~MethodArea ()
MethodArea ()
Private Attributes
vector< ClassFile * > classes
MethodInfo * main_method
Static Private Attributes
static MethodArea * instance = NULL
Detailed Description
Definition at line 11 of file method_area.hpp.
Constructor & Destructor Documentation
~MethodArea()
MethodArea::~MethodArea () private
Definition at line 101 of file method_area.cpp.
{
   for(uint i =0;i<this->classes.size();i+=1){
     ClassFile* f = this->classes[i];
     delete f;
   }
   this->classes.clear();
 }
References classes.
MethodArea()
MethodArea::MethodArea () inline private
Definition at line 19 of file method_area.hpp.
 {};
Referenced by getInstance().
Member Function Documentation
classHasMethod()
bool MethodArea::classHasMethod (string class_name, string method_name, string args_descriptor)
Definition at line 91 of file method_area.cpp.
{
   try{
     this->getMethodByName(class_name, method_name, descriptor);
     return true;
   }
   catch(const std::exception& e){
     return false;
   }
 }
References getMethodByName().
Referenced by ClassLoader::initializeClass().
getClassFile()
ClassFile * MethodArea::getClassFile (string class_name)
Definition at line 71 of file method_area.cpp.
{
   for(uint16_t i=0;i<this->classes.size();i+=1){
     string evaluated_class_name = this->classes[i]->getThisClassName();
     if(evaluated_class_name == class_name){
       return this->classes[i];
     }
   }
   throw runtime_error("ClassError: " + class_name + " nao encontrado");
 }
References classes.
Referenced by ClassLoader::classIs(), JVMClass::getFieldsFor(), getMethodByName(), ClassLoader::initializeClass(), InterfaceLoader::initializeInterface(), insertNewClass(), InterfaceLoader::interfaceIs(), isAlreadyIncluded(), JVMClass::JVMClass(), InterfaceLoader::linkInterface(), ClassLoader::resolveClass(), and InterfaceLoader::resolveInterface().
getInstance()
MethodArea * MethodArea::getInstance () static
Definition at line 6 of file method_area.cpp.
{
   if(MethodArea::instance == NULL) {
     MethodArea::instance = new MethodArea();
   }
   return MethodArea::instance;
 }
References instance, and MethodArea().
Referenced by JVMClass::getFieldsFor(), JVMClass::JVMClass(), and ExecutionEngine::loadMethodArea().
getMainMethod()
MethodInfo * MethodArea::getMainMethod ()
Definition at line 66 of file method_area.cpp.
{
   // TODO: Dar throw caso main_method nao tenha sido setado;
   return this->main_method;
 }
References main_method.
Referenced by Thread::runMain(), and ExecutionEngine::start().
getMethodByName()
MethodInfo * MethodArea::getMethodByName (string class_name, string methodName, string args_descriptor)
Definition at line 46 of file method_area.cpp.
{
   ClassFile* class_file = this->getClassFile(class_name);
   // cout << "Procurando na classe: " << class_name << endl;
   for(uint32_t i=0; i<class_file->methods.size();i+=1){
     MethodInfo* current_method = class_file->methods[i];
     if(current_method->getName() == methodName
       && current_method->getDescriptorString() == descriptor
     ){
       return current_method;
     }
   }
   if( class_file->getSuperClassName() != "java/lang/Object" ){
     return this->getMethodByName(class_file->getSuperClassName(), methodName, descriptor);
   }
   throw runtime_error("MethodError: " + methodName + " nao encontrado");
 }
References getClassFile(), MethodInfo::getDescriptorString(), MethodInfo::getName(), ClassFile::getSuperClassName(), and ClassFile::methods.
Referenced by classHasMethod(), Thread::invokeInstanceMethod(), and Thread::invokeStaticMethod().
insertNewClass()
ClassFile * MethodArea::insertNewClass (string class_name)
Definition at line 18 of file method_area.cpp.
{
   if(this->isAlreadyIncluded(class_name)){
     return this->getClassFile(class_name);
   }
   if(class_name == "java/lang/Object") class_name = "Object";
   ClassFile* new_class = new ClassFile(class_name);
   new_class->loadClass();
   this->classes.push_back(new_class);
   this->searchMainMethod(new_class);
   return new_class;
 }
References classes, getClassFile(), isAlreadyIncluded(), ClassFile::loadClass(), and searchMainMethod().
Referenced by ClassLoader::loadClass().
isAlreadyIncluded()
bool MethodArea::isAlreadyIncluded (string class_name)
Definition at line 81 of file method_area.cpp.
{
   try{
     this->getClassFile(class_name);
     return true;
   }
   catch(const std::exception& e){
     return false;
   }
 }
References getClassFile().
Referenced by insertNewClass().
realeaseInstance()
void MethodArea::realeaseInstance () static
Definition at line 12 of file method_area.cpp.
{
   if(MethodArea::instance != NULL) {
     delete MethodArea::instance;
     MethodArea::instance = NULL;
   }
 }
References instance.
Referenced by ExecutionEngine::~ExecutionEngine().
searchMainMethod()
void MethodArea::searchMainMethod (ClassFile * classfile) private
Definition at line 35 of file method_area.cpp.
{
   for(uint32_t i=0; i<classfile->methods.size();i+=1){
     MethodInfo* current_method = classfile->methods[i];
     // TODO: verificar public static
     if(current_method->getName() == "main"){
       this->main_method = current_method;
     }
   }
 }
References MethodInfo::getName(), main_method, and ClassFile::methods.
Referenced by insertNewClass().
Field Documentation
classes
vector<ClassFile*> MethodArea::classes private
Definition at line 13 of file method_area.hpp.
Referenced by getClassFile(), insertNewClass(), and ~MethodArea().
instance
MethodArea * MethodArea::instance = NULL static private
Definition at line 20 of file method_area.hpp.
Referenced by getInstance(), and realeaseInstance().
main_method
MethodInfo* MethodArea::main_method private
Definition at line 15 of file method_area.hpp.
Referenced by getMainMethod(), and searchMainMethod().
The documentation for this class was generated from the following files:
include/interpretador/method_area.hpp
src/interpretador/method_area.cpp