SB-2020-2-JVM: Instructions::Jsr Class Reference
Instructions::Jsr Class Reference
#include <jsr.hpp>
Public Member Functions
Jsr (Attribute::CodeAttribute *code_attr, uint8_t opcode)
string toString ()
int execute (Frame *frame)
Public Member Functions inherited from Instructions::BaseInstruction
BaseInstruction (Attribute::CodeAttribute *code_attr, uint8_t opcode)
virtual ~BaseInstruction ()
virtual void print ()
virtual void print (int)
Private Attributes
uint16_t branch_bytes
Additional Inherited Members
Static Public Member Functions inherited from Instructions::BaseInstruction
static string getTypePrefix (uint8_t type)
static BaseInstruction * getInstance (Attribute::CodeAttribute *code_attr, uint8_t opcode, uint32_t pc)
Data Fields inherited from Instructions::BaseInstruction
uint8_t opcode
uint16_t pc
Protected Member Functions inherited from Instructions::BaseInstruction
string hexToString (int)
string intToString (int)
string intToSignedString (int)
string createStringWithCPRef (string name, uint16_t index)
string tabs (int)
Protected Attributes inherited from Instructions::BaseInstruction
Attribute::CodeAttribute * code_attr
Detailed Description
Definition at line 8 of file jsr.hpp.
Constructor & Destructor Documentation
Jsr()
Jsr::Jsr (Attribute::CodeAttribute * code_attr, uint8_t opcode)
Definition at line 5 of file jsr.cpp.
     :BaseInstruction(code_attr, opcode){
   this->code_attr->class_file->file_reader->readBytes(2, this->branch_bytes);
 }
References branch_bytes, AttributeInfo::class_file, ClassFile::file_reader, and FileReader::readBytes().
Member Function Documentation
execute()
int Jsr::execute (Frame * frame) virtual
Reimplemented from Instructions::BaseInstruction.
Definition at line 14 of file jsr.cpp.
{
   int16_t branch_offset = this->branch_bytes;
   uint32_t base_adress = frame->local_pc;
   //***
   frame->operand_stack.push(base_adress, ReturnAdress);
   frame->local_pc = base_adress + branch_offset;
   return frame->local_pc;
 }
References branch_bytes, Frame::local_pc, Frame::operand_stack, OperandStack::push(), and ReturnAdress.
toString()
string Jsr::toString () virtual
Reimplemented from Instructions::BaseInstruction.
Definition at line 10 of file jsr.cpp.
                     {
   return "jsr " + this->intToString(this->branch_bytes);
 }
References branch_bytes, and Instructions::BaseInstruction::intToString().
Field Documentation
branch_bytes
uint16_t Instructions::Jsr::branch_bytes private
Definition at line 10 of file jsr.hpp.
Referenced by execute(), Jsr(), and toString().
The documentation for this class was generated from the following files:
include/attribute_info_classes/instruction_classes/jsr.hpp
src/attribute_info_classes/instruction_classes/jsr.cpp