SB-2020-2-JVM: PrimitiveType Class Reference
PrimitiveType Class Reference
#include <primitive_type.hpp>
Public Member Functions
PrimitiveType (uint64_t x, JVMType type)
void print ()
string toString ()
Public Member Functions inherited from ElementType
ElementType (JVMType type)
Public Member Functions inherited from ComponentType
ComponentType (JVMType component_type)
void setReference (int)
int getReference ()
virtual ~ComponentType ()
Data Fields
uint64_t data
Data Fields inherited from ComponentType
JVMType type
Additional Inherited Members
Static Public Member Functions inherited from ComponentType
static ComponentType * getDefaultValue (JVMType)
static JVMType getTypeFromDescriptor (string descriptor)
Protected Attributes inherited from ComponentType
int heap_reference
Detailed Description
Definition at line 13 of file primitive_type.hpp.
Constructor & Destructor Documentation
PrimitiveType()
PrimitiveType::PrimitiveType (uint64_t x, JVMType type)
Definition at line 31 of file primitive_type.cpp.
                                                     :ElementType(type){
   this->data =x;
 };
References data.
Member Function Documentation
print()
void PrimitiveType::print () virtual
Reimplemented from ComponentType.
Definition at line 35 of file primitive_type.cpp.
{
     std::cout << "<" << this->toString() << ", " << this->type << ">" << endl;
 }
References toString(), and ComponentType::type.
toString()
string PrimitiveType::toString () virtual
Reimplemented from ComponentType.
Definition at line 39 of file primitive_type.cpp.
{
   stringstream paramString;
   if(this->type == Double){
     paramString << to_string(*(double*)&this->data);
   }
   else if(this->type == Float){
     paramString << to_string(*(float*)&this->data);
   }
   else if(this->type == Int){
     paramString << to_string(*(int*)&this->data);
   }
   else if(this->type == Long){
     paramString << to_string(*(int64_t*)&this->data);
   }
   else if(this->type == Byte){
     paramString << to_string(*(int8_t*)&this->data);
   }
   else if(this->type == Short){
     paramString << to_string(*(int16_t*)&this->data);
   }
   else if(this->type == Char){
     uint16_t x ;
     x = (uint16_t)this->data;
     char chars[5];
     GetUnicodeChar(x, chars);
     paramString << chars ;
   }
   else if(this->type == Boolean){
     if(this->data) paramString << "true";
     else paramString << "false";
   }
   else paramString << this->data;
   return paramString.str();
 }
References Boolean, Byte, Char, data, Double, Float, GetUnicodeChar(), Int, Long, Short, and ComponentType::type.
Referenced by InvokeSimulation::exceptionInit(), LocalVariable::print(), print(), and InvokeSimulation::println().
Field Documentation
data
uint64_t PrimitiveType::data
Definition at line 15 of file primitive_type.hpp.
Referenced by Instructions::GetField::execute(), Instructions::InterfaceAload::execute(), Instructions::GetStatic::execute(), ArrayType::getIndexAsAsPrimitiveType(), OperandStack::pop(), PrimitiveType(), ArrayType::print(), and toString().
The documentation for this class was generated from the following files:
include/interpretador/types/primitive_type.hpp
src/interpretador/types/primitive_type.cpp