SB-2020-2-JVM: Instructions::InvokeInterface Class Reference
Instructions::InvokeInterface Class Reference
#include <invokeinterface.hpp>
Public Member Functions
InvokeInterface (Attribute::CodeAttribute *code_attr, uint8_t opcode)
string toString ()
Public Member Functions inherited from Instructions::BaseInstruction
BaseInstruction (Attribute::CodeAttribute *code_attr, uint8_t opcode)
virtual ~BaseInstruction ()
virtual void print ()
virtual void print (int)
virtual int execute (Frame *frame)
Private Attributes
uint16_t index
uint8_t count
uint8_t zero
Additional Inherited Members
Static Public Member Functions inherited from Instructions::BaseInstruction
static string getTypePrefix (uint8_t type)
static BaseInstruction * getInstance (Attribute::CodeAttribute *code_attr, uint8_t opcode, uint32_t pc)
Data Fields inherited from Instructions::BaseInstruction
uint8_t opcode
uint16_t pc
Protected Member Functions inherited from Instructions::BaseInstruction
string hexToString (int)
string intToString (int)
string intToSignedString (int)
string createStringWithCPRef (string name, uint16_t index)
string tabs (int)
Protected Attributes inherited from Instructions::BaseInstruction
Attribute::CodeAttribute * code_attr
Detailed Description
Definition at line 8 of file invokeinterface.hpp.
Constructor & Destructor Documentation
InvokeInterface()
InvokeInterface::InvokeInterface (Attribute::CodeAttribute * code_attr, uint8_t opcode)
Definition at line 5 of file invokeinterface.cpp.
     :BaseInstruction(code_attr, opcode){
   FileReader *f_reader = this->code_attr->class_file->file_reader;
   f_reader->readBytes(2, this->index);
   f_reader->readBytes(1, this->count);
   f_reader->readBytes(1, this->zero);
 }
References AttributeInfo::class_file, count, ClassFile::file_reader, index, FileReader::readBytes(), and zero.
Member Function Documentation
toString()
string InvokeInterface::toString () virtual
Reimplemented from Instructions::BaseInstruction.
Definition at line 13 of file invokeinterface.cpp.
{
   return this->createStringWithCPRef("invokeinterface", this->index)
   + " count: " + this->intToString(this->count);
 }
References count, Instructions::BaseInstruction::createStringWithCPRef(), index, and Instructions::BaseInstruction::intToString().
Field Documentation
count
uint8_t Instructions::InvokeInterface::count private
Definition at line 11 of file invokeinterface.hpp.
Referenced by InvokeInterface(), and toString().
index
uint16_t Instructions::InvokeInterface::index private
Definition at line 10 of file invokeinterface.hpp.
Referenced by InvokeInterface(), and toString().
zero
uint8_t Instructions::InvokeInterface::zero private
Definition at line 12 of file invokeinterface.hpp.
Referenced by InvokeInterface().
The documentation for this class was generated from the following files:
include/attribute_info_classes/instruction_classes/invokeinterface.hpp
src/attribute_info_classes/instruction_classes/invokeinterface.cpp