SB-2020-2-JVM: Attribute::SourceFile Class Reference
Attribute::SourceFile Class Reference
#include <source_file.hpp>
Public Member Functions
SourceFile (AttrInitialValue initial_value)
void printInfo (int n_tabs)
string getFileName ()
Public Member Functions inherited from AttributeInfo
AttributeInfo (Attribute::AttrInitialValue initial)
virtual ~AttributeInfo ()
string getAttributeName ()
Private Member Functions
string removeSubString (string initial, string sub_string)
Private Attributes
uint16_t sourcefile_index
Additional Inherited Members
Static Public Member Functions inherited from AttributeInfo
static AttributeInfo * getInstance (ClassFile *class_file)
static string createTabs (int n_tabs)
static void loadAttributes (vector< AttributeInfo * > &attributes, uint16_t size, ClassFile *class_file)
static void printAttributes (vector< AttributeInfo * > attributes, int n_tabs)
Data Fields inherited from AttributeInfo
ClassFile * class_file
Protected Attributes inherited from AttributeInfo
uint16_t attribute_name_index
uint32_t attribute_length
Detailed Description
Definition at line 7 of file source_file.hpp.
Constructor & Destructor Documentation
SourceFile()
Attribute::SourceFile::SourceFile (AttrInitialValue initial_value)
Definition at line 3 of file source_file.cpp.
     :AttributeInfo(initial_value)
   {
   this->class_file->setAttribute(2, this->sourcefile_index);
   string cp_file_name = this->class_file->getConstantPoolUtf8String(this->sourcefile_index);
   string source_file_name = this->class_file->file_reader->getFileName();
   if(source_file_name.find(this->removeSubString(cp_file_name, ".java") + ".class") == std::string::npos){
     if( this->class_file->beautifiedMajorVersion() == "[1.2]" )
       throw std::invalid_argument("java.lang.NoClassDefFoundError: --- (wrong name: ---)");
   }
 }
References ClassFile::beautifiedMajorVersion(), AttributeInfo::class_file, ClassFile::file_reader, ClassFile::getConstantPoolUtf8String(), FileReader::getFileName(), ClassFile::setAttribute(), and sourcefile_index.
Member Function Documentation
getFileName()
string Attribute::SourceFile::getFileName ()
Definition at line 23 of file source_file.cpp.
{
   return this->class_file->getConstantPoolUtf8String(this->sourcefile_index);
 }
printInfo()
void Attribute::SourceFile::printInfo (int n_tabs) virtual
Reimplemented from AttributeInfo.
Definition at line 17 of file source_file.cpp.
{
   AttributeInfo::printInfo(n_tabs);
   cout << createTabs(n_tabs+1) << "Source file name index: #" << this->sourcefile_index;
   cout << " <" << this->getFileName() << ">" << endl;
 }
References AttributeInfo::printInfo().
removeSubString()
string Attribute::SourceFile::removeSubString (string initial, string sub_string) private
Definition at line 27 of file source_file.cpp.
{
   std::string::size_type sub_string_size = initial.find(sub_string);
   if (sub_string_size != std::string::npos){
     return initial.erase(sub_string_size, sub_string.length());
   }else {
     return initial;
   }
 }
Field Documentation
sourcefile_index
uint16_t Attribute::SourceFile::sourcefile_index private
Definition at line 8 of file source_file.hpp.
Referenced by SourceFile().
The documentation for this class was generated from the following files:
include/attribute_info_classes/source_file.hpp
src/attribute_info_classes/source_file.cpp