SB-2020-2-JVM: InvokeSimulation Class Reference
InvokeSimulation Class Reference
#include <invoke_simulation.hpp>
Static Public Member Functions
static void println (Frame *, int method_ref_index)
static void stringMethod (string method_name, Frame *, int method_ref_index)
static void exceptionInit (Frame *frame, string exception_name, int method_ref_index)
Static Private Member Functions
static string getResultStringFromArgs (int n_args, Frame *)
Detailed Description
Definition at line 14 of file invoke_simulation.hpp.
Member Function Documentation
exceptionInit()
void InvokeSimulation::exceptionInit (Frame * frame, string exception_name, int method_ref_index) static
Definition at line 66 of file invoke_simulation.cpp.
{
   CP::MethodRefInfo* m_i = (CP::MethodRefInfo*)frame->current_method->class_file->getConstantPoolEntry(method_ref_index);
   string args_descriptor = m_i->getDescriptor();
   string args;
   int n_args = MethodInfo::getArgsCountOn(args_descriptor);
   for(int i=0;i<n_args;i++){
     pair<uint64_t, JVMType> arg_pair = frame->operand_stack.pop();
     if(arg_pair.second == Reference){
       ComponentType* arg = Heap::getInstance()->getReference(arg_pair.first);
       args += arg->toString();
     }
     else{
       PrimitiveType* x = new PrimitiveType(arg_pair.first, arg_pair.second);
       args += x->toString();
     }
   }
   pair<uint64_t, JVMType> val = frame->operand_stack.pop();
   ExceptionType* exception = (ExceptionType*) Heap::getInstance()->getReference(val.first);
   exception->setArgs(args);
 }
References MethodInfo::class_file, Frame::current_method, MethodInfo::getArgsCountOn(), ClassFile::getConstantPoolEntry(), CP::MethodRefInfo::getDescriptor(), Heap::getInstance(), Heap::getReference(), Frame::operand_stack, OperandStack::pop(), Reference, ExceptionType::setArgs(), ComponentType::toString(), and PrimitiveType::toString().
Referenced by Instructions::InvokeSpecial::execute().
getResultStringFromArgs()
string InvokeSimulation::getResultStringFromArgs (int n_args, Frame * frame) static private
Definition at line 25 of file invoke_simulation.cpp.
{
   string resultString;
   for(int i=0;i<n_args;i++){
     pair<uint64_t, JVMType> val = frame->operand_stack.pop();
     ComponentType* arg = Heap::getInstance()->getReference(val.first);
     resultString += arg->toString();
   }
   return resultString;
 }
References Heap::getInstance(), Heap::getReference(), Frame::operand_stack, OperandStack::pop(), and ComponentType::toString().
Referenced by stringMethod().
println()
void InvokeSimulation::println (Frame * frame, int method_ref_index) static
Definition at line 4 of file invoke_simulation.cpp.
{
   CP::MethodRefInfo* m_i = (CP::MethodRefInfo*)frame->current_method->class_file->getConstantPoolEntry(method_ref_index);
   string args_descriptor = m_i->getDescriptor();
   int n_args = MethodInfo::getArgsCountOn(args_descriptor);
   for(int i=0;i<n_args;i++){
     pair<uint64_t, JVMType> val = frame->operand_stack.pop();
     if(val.second == Reference){
       ComponentType* x = Heap::getInstance()->getReference(val.first);
       cout << x->toString();
     }
     else{
       PrimitiveType*x = new PrimitiveType(val.first, val.second);
       cout << x->toString();
     }
   }
   cout << endl;
   frame->operand_stack.pop();
 }
References MethodInfo::class_file, Frame::current_method, MethodInfo::getArgsCountOn(), ClassFile::getConstantPoolEntry(), CP::MethodRefInfo::getDescriptor(), Heap::getInstance(), Heap::getReference(), Frame::operand_stack, OperandStack::pop(), Reference, ComponentType::toString(), and PrimitiveType::toString().
Referenced by Instructions::InvokeVirtual::execute().
stringMethod()
void InvokeSimulation::stringMethod (string method_name, Frame * frame, int method_ref_index) static
Definition at line 35 of file invoke_simulation.cpp.
{
   CP::MethodRefInfo* m_i = (CP::MethodRefInfo*)frame->current_method->class_file->getConstantPoolEntry(method_index);
   string args_descriptor = m_i->getDescriptor();
   int n_args = MethodInfo::getArgsCountOn(args_descriptor);
   if(method_name == "append"){
     string resultString = InvokeSimulation::getResultStringFromArgs(n_args, frame);
     pair<uint64_t, JVMType> val = frame->operand_stack.pop();
     ComponentType* baseString = Heap::getInstance()->getReference(val.first);
     int ref = Heap::getInstance()->storeComponent(new StringType(baseString->toString() + resultString));
     frame->operand_stack.push(ref, Reference);
     return;
   }
   if(method_name == "<init>"){
     string resultString = InvokeSimulation::getResultStringFromArgs(n_args, frame);
     pair<uint64_t, JVMType> val = frame->operand_stack.pop();
     StringType* baseString = (StringType*) Heap::getInstance()->getReference(val.first);
     baseString->value = resultString;
     return;
   }
   if(method_name == "toString"){
     return;
   }
   throw std::runtime_error("MethodError: Metodo "+method_name+"  -  da classe string nao suportado");
 }
References MethodInfo::class_file, Frame::current_method, MethodInfo::getArgsCountOn(), ClassFile::getConstantPoolEntry(), CP::MethodRefInfo::getDescriptor(), Heap::getInstance(), Heap::getReference(), getResultStringFromArgs(), Frame::operand_stack, OperandStack::pop(), OperandStack::push(), Reference, Heap::storeComponent(), ComponentType::toString(), and StringType::value.
Referenced by Instructions::InvokeVirtual::execute(), and Instructions::InvokeSpecial::execute().
The documentation for this class was generated from the following files:
include/interpretador/invoke_simulation.hpp
src/interpretador/invoke_simulation.cpp