SB-2020-2-JVM: LocalVariable Class Reference
LocalVariable Class Reference
#include <local_variable.hpp>
Public Member Functions
void initialize (uint32_t max_length)
pair< uint64_t, JVMType > get (int index)
void insert (int index, uint64_t data, JVMType type)
void print ()
Private Attributes
vector< PrimitiveType * > local_variables
Detailed Description
Definition at line 11 of file local_variable.hpp.
Member Function Documentation
get()
pair< uint64_t, JVMType > LocalVariable::get (int index)
Definition at line 19 of file local_variable.cpp.
{
   pair<uint64_t, JVMType> returnVal;
   returnVal.first = this->local_variables[index]->data;
   returnVal.second = this->local_variables[index]->type;
   return returnVal;
 }
References local_variables.
Referenced by Instructions::Inc::execute(), Instructions::AbstractLoad::execute(), and print().
initialize()
void LocalVariable::initialize (uint32_t max_length)
Definition at line 3 of file local_variable.cpp.
{
   for (std::size_t i = 0; i < max_length; i++){
     PrimitiveType* defaultValue = new PrimitiveType(0, Int);
     this->local_variables.push_back(defaultValue);
   }
 }
References Int, and local_variables.
Referenced by Frame::Frame().
insert()
void LocalVariable::insert (int index, uint64_t data, JVMType type)
Definition at line 26 of file local_variable.cpp.
{
   this->local_variables[index]->data = data;
   this->local_variables[index]->type = type;
 }
References local_variables.
Referenced by Instructions::Inc::execute(), Instructions::AbstractStore::execute(), and Thread::initializeFrameVariableVector().
print()
void LocalVariable::print ()
Definition at line 10 of file local_variable.cpp.
{
   cout << "[";
   for (std::size_t i = 0; i < this->local_variables.size(); i++){
     PrimitiveType p(this->get(i).first, this->get(i).second);
     cout << p.toString() << ", ";
   }
   cout << "]"<< endl;
 }
References get(), local_variables, and PrimitiveType::toString().
Field Documentation
local_variables
vector<PrimitiveType*> LocalVariable::local_variables private
Definition at line 13 of file local_variable.hpp.
Referenced by get(), initialize(), insert(), and print().
The documentation for this class was generated from the following files:
include/interpretador/local_variable.hpp
src/interpretador/local_variable.cpp