SB-2020-2-JVM: Heap Class Reference
Heap Class Reference
#include <heap.hpp>
Public Member Functions
ComponentType * getReference (int reference_id)
int storeComponent (ComponentType *)
int createPrimitiveTypeArray (int n_dimensions, JVMType arrayType)
Static Public Member Functions
static Heap * getInstance ()
static void releaseInstance ()
Private Member Functions
Heap ()
~Heap ()
Private Attributes
vector< ComponentType * > heap_store
int size =0
Static Private Attributes
static Heap * instance = NULL
Detailed Description
Definition at line 9 of file heap.hpp.
Constructor & Destructor Documentation
Heap()
Heap::Heap () inline private
Definition at line 14 of file heap.hpp.
 {}
Referenced by getInstance().
~Heap()
Heap::~Heap () private
Definition at line 43 of file heap.cpp.
            {
   for(uint i=0 ;i<this->heap_store.size(); i++){
     ComponentType* c = this->heap_store[i];
     delete c;
   }
   this->heap_store.clear();
 }
References heap_store.
Member Function Documentation
createPrimitiveTypeArray()
int Heap::createPrimitiveTypeArray (int n_dimensions, JVMType arrayType)
Definition at line 22 of file heap.cpp.
{
   ArrayType* newArray = new ArrayType(arrayType);
   for(int i=0;i<length;i++){
     PrimitiveType* defaultValue = new PrimitiveType(0, arrayType);
     this->storeComponent(defaultValue);
     newArray->insert(defaultValue);
   }
   this->storeComponent(newArray);
   return newArray->getReference();
 }
References ComponentType::getReference(), ArrayType::insert(), and storeComponent().
getInstance()
Heap * Heap::getInstance () static
Definition at line 9 of file heap.cpp.
{
   if(Heap::instance == NULL){
     Heap::instance = new Heap();
   }
   return Heap::instance;
 }
References Heap(), and instance.
Referenced by ReferenceResolver::allocateArray(), ComponentType::ComponentType(), InvokeSimulation::exceptionInit(), Instructions::ArrayLength::execute(), Instructions::GetField::execute(), Instructions::New::execute(), Instructions::PutField::execute(), Instructions::Athrow::execute(), JVMClass::getFieldsFor(), InvokeSimulation::getResultStringFromArgs(), Thread::handleException(), JVMClass::initializeFields(), JVMField::JVMField(), ClassLoader::linkClass(), InterfaceLoader::linkInterface(), ExecutionEngine::loadMethodArea(), ArrayType::print(), InvokeSimulation::println(), ReferenceResolver::resolveObjectByDescriptor(), ReferenceResolver::resolveStaticFieldSymbolicReference(), JVMField::setData(), InvokeSimulation::stringMethod(), and Thread::Thread().
getReference()
ComponentType * Heap::getReference (int reference_id)
Definition at line 51 of file heap.cpp.
{
   if(reference_id < 0) throw runtime_error("HeapError: Invalid heap access.");
   return this->heap_store[reference_id];
 }
References heap_store.
Referenced by InvokeSimulation::exceptionInit(), Instructions::ArrayLength::execute(), Instructions::GetField::execute(), Instructions::PutField::execute(), Instructions::InterfaceAload::execute(), Instructions::InterfaceAstore::execute(), Instructions::Athrow::execute(), InvokeSimulation::getResultStringFromArgs(), ArrayType::print(), InvokeSimulation::println(), ReferenceResolver::resolveStaticFieldSymbolicReference(), and InvokeSimulation::stringMethod().
releaseInstance()
void Heap::releaseInstance () static
Definition at line 15 of file heap.cpp.
{
   if(Heap::instance != NULL){
     delete Heap::instance;
     Heap::instance=NULL;
   }
 }
References instance.
Referenced by ExecutionEngine::~ExecutionEngine().
storeComponent()
int Heap::storeComponent (ComponentType * toStore)
Definition at line 33 of file heap.cpp.
{
   if(toStore->getReference() >= 0) return toStore->getReference();
   this->heap_store.push_back(toStore);
   int newElementIndex = this->heap_store.size()-1;
   toStore->setReference(newElementIndex);
   return newElementIndex;
 }
References ComponentType::getReference(), heap_store, and ComponentType::setReference().
Referenced by ReferenceResolver::allocateArray(), ComponentType::ComponentType(), createPrimitiveTypeArray(), Instructions::New::execute(), Instructions::Ldc::execute(), Instructions::LdcW::execute(), Instructions::NewArray::execute(), JVMClass::getFieldsFor(), Thread::handleException(), JVMClass::initializeFields(), JVMField::JVMField(), ClassLoader::linkClass(), InterfaceLoader::linkInterface(), ReferenceResolver::resolveObjectByDescriptor(), JVMField::setData(), and InvokeSimulation::stringMethod().
Field Documentation
heap_store
vector<ComponentType*> Heap::heap_store private
Definition at line 12 of file heap.hpp.
Referenced by getReference(), storeComponent(), and ~Heap().
instance
Heap * Heap::instance = NULL static private
Definition at line 11 of file heap.hpp.
Referenced by getInstance(), and releaseInstance().
size
int Heap::size =0 private
Definition at line 13 of file heap.hpp.
The documentation for this class was generated from the following files:
include/interpretador/heap.hpp
src/interpretador/heap.cpp