SB-2020-2-JVM: Instructions::Inc Class Reference
Instructions::Inc Class Reference
#include <inc.hpp>
Public Member Functions
Inc (Attribute::CodeAttribute *code_attr, uint8_t opcode)
string toString ()
int execute (Frame *)
Public Member Functions inherited from Instructions::BaseInstruction
BaseInstruction (Attribute::CodeAttribute *code_attr, uint8_t opcode)
virtual ~BaseInstruction ()
virtual void print ()
virtual void print (int)
Private Attributes
const uint8_t BASE_OPCODE = 0x84
uint8_t type
uint8_t _index
uint8_t _const
Additional Inherited Members
Static Public Member Functions inherited from Instructions::BaseInstruction
static string getTypePrefix (uint8_t type)
static BaseInstruction * getInstance (Attribute::CodeAttribute *code_attr, uint8_t opcode, uint32_t pc)
Data Fields inherited from Instructions::BaseInstruction
uint8_t opcode
uint16_t pc
Protected Member Functions inherited from Instructions::BaseInstruction
string hexToString (int)
string intToString (int)
string intToSignedString (int)
string createStringWithCPRef (string name, uint16_t index)
string tabs (int)
Protected Attributes inherited from Instructions::BaseInstruction
Attribute::CodeAttribute * code_attr
Detailed Description
Definition at line 8 of file inc.hpp.
Constructor & Destructor Documentation
Inc()
Inc::Inc (Attribute::CodeAttribute * code_attr, uint8_t opcode)
Definition at line 5 of file inc.cpp.
     :BaseInstruction(code_attr, opcode){
   this->type = this->opcode - this->BASE_OPCODE;
   FileReader *f = this->code_attr->class_file->file_reader;
   f->readBytes(1, this->_index);
   f->readBytes(1, this->_const);
 }
References _const, _index, BASE_OPCODE, AttributeInfo::class_file, ClassFile::file_reader, FileReader::readBytes(), and type.
Member Function Documentation
execute()
int Inc::execute (Frame * frame) virtual
Reimplemented from Instructions::BaseInstruction.
Definition at line 22 of file inc.cpp.
{
   pair<uint64_t, JVMType> val = frame->local_variables.get(this->_index);
   val.first = (int)val.first + (int8_t)this->_const;
   frame->local_variables.insert(this->_index, val.first, val.second);
   return frame->local_pc+=3;
 }
References _const, _index, LocalVariable::get(), LocalVariable::insert(), Frame::local_pc, and Frame::local_variables.
toString()
string Inc::toString () virtual
Reimplemented from Instructions::BaseInstruction.
Definition at line 14 of file inc.cpp.
                     {
   return BaseInstruction::getTypePrefix(this->type) +
   "inc " +
   this->intToString(this->_index) +
   " by " +
   this->intToString(this->_const)  ;
 }
References _const, _index, Instructions::BaseInstruction::getTypePrefix(), Instructions::BaseInstruction::intToString(), and type.
Field Documentation
_const
uint8_t Instructions::Inc::_const private
Definition at line 12 of file inc.hpp.
Referenced by execute(), Inc(), and toString().
_index
uint8_t Instructions::Inc::_index private
Definition at line 11 of file inc.hpp.
Referenced by execute(), Inc(), and toString().
BASE_OPCODE
const uint8_t Instructions::Inc::BASE_OPCODE = 0x84 private
Definition at line 9 of file inc.hpp.
Referenced by Inc().
type
uint8_t Instructions::Inc::type private
Definition at line 10 of file inc.hpp.
Referenced by Inc(), and toString().
The documentation for this class was generated from the following files:
include/attribute_info_classes/instruction_classes/inc.hpp
src/attribute_info_classes/instruction_classes/inc.cpp