SB-2020-2-JVM: Instructions::Jsr_W Class Reference
Instructions::Jsr_W Class Reference
#include <jsr_w.hpp>
Public Member Functions
Jsr_W (Attribute::CodeAttribute *code_attr, uint8_t opcode)
string toString ()
Public Member Functions inherited from Instructions::BaseInstruction
BaseInstruction (Attribute::CodeAttribute *code_attr, uint8_t opcode)
virtual ~BaseInstruction ()
virtual void print ()
virtual void print (int)
virtual int execute (Frame *frame)
Private Attributes
int32_t branch_bytes
Additional Inherited Members
Static Public Member Functions inherited from Instructions::BaseInstruction
static string getTypePrefix (uint8_t type)
static BaseInstruction * getInstance (Attribute::CodeAttribute *code_attr, uint8_t opcode, uint32_t pc)
Data Fields inherited from Instructions::BaseInstruction
uint8_t opcode
uint16_t pc
Protected Member Functions inherited from Instructions::BaseInstruction
string hexToString (int)
string intToString (int)
string intToSignedString (int)
string createStringWithCPRef (string name, uint16_t index)
string tabs (int)
Protected Attributes inherited from Instructions::BaseInstruction
Attribute::CodeAttribute * code_attr
Detailed Description
Definition at line 8 of file jsr_w.hpp.
Constructor & Destructor Documentation
Jsr_W()
Jsr_W::Jsr_W (Attribute::CodeAttribute * code_attr, uint8_t opcode)
Definition at line 5 of file jsr_w.cpp.
     :BaseInstruction(code_attr, opcode){
   this->code_attr->class_file->file_reader->readBytes(2, this->branch_bytes);
 }
References branch_bytes, AttributeInfo::class_file, ClassFile::file_reader, and FileReader::readBytes().
Member Function Documentation
toString()
string Jsr_W::toString () virtual
Reimplemented from Instructions::BaseInstruction.
Definition at line 10 of file jsr_w.cpp.
                       {
   return "jsr_w " +
     this->intToString(this->branch_bytes + this->pc) +
     " (" + this->intToSignedString(this->branch_bytes) +")"
     ;
 }
References branch_bytes, Instructions::BaseInstruction::intToSignedString(), Instructions::BaseInstruction::intToString(), and Instructions::BaseInstruction::pc.
Field Documentation
branch_bytes
int32_t Instructions::Jsr_W::branch_bytes private
Definition at line 10 of file jsr_w.hpp.
Referenced by Jsr_W(), and toString().
The documentation for this class was generated from the following files:
include/attribute_info_classes/instruction_classes/jsr_w.hpp
src/attribute_info_classes/instruction_classes/jsr_w.cpp