SB-2020-2-JVM: InterfaceLoader Class Reference
InterfaceLoader Class Reference
#include <interface_loader.hpp>
Static Public Member Functions
static int resolveInterface (string interface_name, MethodArea *)
static PrimitiveType * resolveSymbol (Heap *, MethodArea *, string symbol)
Static Private Member Functions
static bool interfaceIs (ClassFileState state, string interface_name, MethodArea *method_area)
static bool interfaceIsNot (ClassFileState state, string interface_name, MethodArea *method_area)
static void linkInterface (string interface_name, MethodArea *)
static void initializeInterface (string interface_name, MethodArea *)
Detailed Description
Definition at line 17 of file interface_loader.hpp.
Member Function Documentation
initializeInterface()
void InterfaceLoader::initializeInterface (string interface_name, MethodArea * method_area) static private
Definition at line 33 of file interface_loader.cpp.
{
     ClassFile* interface_file = method_area->getClassFile(interface_name);
     Thread* main_thread =  ExecutionEngine::getInstance()->main_thread;
     interface_file->state = INITIALIZED;
 }
References MethodArea::getClassFile(), ExecutionEngine::getInstance(), INITIALIZED, ExecutionEngine::main_thread, and ClassFile::state.
Referenced by resolveInterface().
interfaceIs()
bool InterfaceLoader::interfaceIs (ClassFileState state, string interface_name, MethodArea * method_area) static private
Definition at line 42 of file interface_loader.cpp.
{
     ClassFile* interface_file = method_area->getClassFile(interface_name);
     return interface_file->state >= state;
 }
References MethodArea::getClassFile(), and ClassFile::state.
Referenced by interfaceIsNot().
interfaceIsNot()
bool InterfaceLoader::interfaceIsNot (ClassFileState state, string interface_name, MethodArea * method_area) static private
Definition at line 47 of file interface_loader.cpp.
{
     return !InterfaceLoader::interfaceIs(state, interface_name, method_area);
 }
References interfaceIs().
Referenced by resolveInterface().
linkInterface()
void InterfaceLoader::linkInterface (string interface_name, MethodArea * method_area) static private
Definition at line 10 of file interface_loader.cpp.
{
     Heap* heap = Heap::getInstance();
     JVMInterface* linking_interface = new JVMInterface(interface_name);
     ClassFile* interface_file = method_area->getClassFile(interface_name);
     linking_interface->setClassFile(interface_file);
     // Link fields
     for(uint16_t i=0;i<interface_file->fields.size();i+=1){
         FieldInfo* field = interface_file->fields[i];
         JVMField* newFieldAlocated = new JVMField(field);
         heap->storeComponent(newFieldAlocated);
         linking_interface->addField(newFieldAlocated);
     }
     interface_file->heap_ref = heap->storeComponent(linking_interface);
     interface_file->state = LINKED;
 }
References JVMInterface::addField(), ClassFile::fields, MethodArea::getClassFile(), Heap::getInstance(), ClassFile::heap_ref, LINKED, JVMInterface::setClassFile(), ClassFile::state, and Heap::storeComponent().
Referenced by resolveInterface().
resolveInterface()
int InterfaceLoader::resolveInterface (string interface_name, MethodArea * method_area) static
Definition at line 51 of file interface_loader.cpp.
{
     if(InterfaceLoader::interfaceIsNot(LOADED, interface_name, method_area)){
         throw runtime_error("LoadError: "+interface_name+" is not loaded");
     }
     if(InterfaceLoader::interfaceIsNot(LINKED, interface_name, method_area)){
         InterfaceLoader::linkInterface(interface_name, method_area);
     }
     if(InterfaceLoader::interfaceIsNot(INITIALIZED, interface_name, method_area)){
         InterfaceLoader::initializeInterface(interface_name, method_area);
     }
     // TODO: Resolver super-interfacees
     ClassFile* interface_file = method_area->getClassFile(interface_name);
     return interface_file->heap_ref;
 }
References MethodArea::getClassFile(), ClassFile::heap_ref, INITIALIZED, initializeInterface(), interfaceIsNot(), LINKED, linkInterface(), and LOADED.
Referenced by ReferenceResolver::resolveInterfaceName().
resolveSymbol()
static PrimitiveType* InterfaceLoader::resolveSymbol (Heap * , MethodArea * , string symbol) static
The documentation for this class was generated from the following files:
include/interpretador/interface_loader.hpp
src/interpretador/interface_loader.cpp