SB-2020-2-JVM: Instructions::PutField Class Reference
Instructions::PutField Class Reference
#include <putfield.hpp>
Public Member Functions
PutField (Attribute::CodeAttribute *code_attr, uint8_t opcode)
string toString ()
int execute (Frame *)
Public Member Functions inherited from Instructions::BaseInstruction
BaseInstruction (Attribute::CodeAttribute *code_attr, uint8_t opcode)
virtual ~BaseInstruction ()
virtual void print ()
virtual void print (int)
Private Attributes
uint16_t indexbyte
Additional Inherited Members
Static Public Member Functions inherited from Instructions::BaseInstruction
static string getTypePrefix (uint8_t type)
static BaseInstruction * getInstance (Attribute::CodeAttribute *code_attr, uint8_t opcode, uint32_t pc)
Data Fields inherited from Instructions::BaseInstruction
uint8_t opcode
uint16_t pc
Protected Member Functions inherited from Instructions::BaseInstruction
string hexToString (int)
string intToString (int)
string intToSignedString (int)
string createStringWithCPRef (string name, uint16_t index)
string tabs (int)
Protected Attributes inherited from Instructions::BaseInstruction
Attribute::CodeAttribute * code_attr
Detailed Description
Definition at line 8 of file putfield.hpp.
Constructor & Destructor Documentation
PutField()
PutField::PutField (Attribute::CodeAttribute * code_attr, uint8_t opcode)
Definition at line 7 of file putfield.cpp.
     :BaseInstruction(code_attr, opcode){
   FileReader *f_reader = this->code_attr->class_file->file_reader;
   f_reader->readBytes(2, this->indexbyte);
 }
References AttributeInfo::class_file, ClassFile::file_reader, indexbyte, and FileReader::readBytes().
Member Function Documentation
execute()
int PutField::execute (Frame * frame) virtual
Reimplemented from Instructions::BaseInstruction.
Definition at line 17 of file putfield.cpp.
{
   string symbolic_ref = frame->current_method->class_file->getConstantPoolEntry(this->indexbyte)->toString();
   string field_name = ReferenceResolver::separateSymbol(symbolic_ref, ".").second;
   pair<uint64_t, JVMType> value = frame->operand_stack.pop();
   pair<uint64_t, JVMType> objref = frame->operand_stack.pop();
   if(objref.second != Reference) throw std::runtime_error("TypeError: Objref is not a reference");
   JVMObject* obj  = (JVMObject*)Heap::getInstance()->getReference(objref.first);
   JVMField* f = obj->getField(field_name);
   f->setData(new PrimitiveType(value.first, value.second));
   frame->local_pc+=3;
   return frame->local_pc;
 }
References MethodInfo::class_file, Frame::current_method, ClassFile::getConstantPoolEntry(), JVMClass::getField(), Heap::getInstance(), Heap::getReference(), indexbyte, Frame::local_pc, Frame::operand_stack, OperandStack::pop(), Reference, ReferenceResolver::separateSymbol(), JVMField::setData(), and CpInfo::toString().
toString()
string PutField::toString () virtual
Reimplemented from Instructions::BaseInstruction.
Definition at line 13 of file putfield.cpp.
{
   return this->createStringWithCPRef("putfield", this->indexbyte);
 }
References Instructions::BaseInstruction::createStringWithCPRef(), and indexbyte.
Field Documentation
indexbyte
uint16_t Instructions::PutField::indexbyte private
Definition at line 10 of file putfield.hpp.
Referenced by execute(), PutField(), and toString().
The documentation for this class was generated from the following files:
include/attribute_info_classes/instruction_classes/putfield.hpp
src/attribute_info_classes/instruction_classes/putfield.cpp