SB-2020-2-JVM: Instructions::AbstractLoad Class Reference
Instructions::AbstractLoad Class Reference abstract
#include <_load.hpp>
Public Member Functions
AbstractLoad (Attribute::CodeAttribute *code_attr, uint8_t opcode, uint8_t _load_opcode, uint8_t _loadn_base_opcode)
virtual string getName ()=0
virtual JVMType getType ()=0
string toString ()
int execute (Frame *frame)
Public Member Functions inherited from Instructions::BaseInstruction
BaseInstruction (Attribute::CodeAttribute *code_attr, uint8_t opcode)
virtual ~BaseInstruction ()
virtual void print ()
virtual void print (int)
Protected Attributes
bool is_n_class
uint8_t param
Protected Attributes inherited from Instructions::BaseInstruction
Attribute::CodeAttribute * code_attr
Additional Inherited Members
Static Public Member Functions inherited from Instructions::BaseInstruction
static string getTypePrefix (uint8_t type)
static BaseInstruction * getInstance (Attribute::CodeAttribute *code_attr, uint8_t opcode, uint32_t pc)
Data Fields inherited from Instructions::BaseInstruction
uint8_t opcode
uint16_t pc
Protected Member Functions inherited from Instructions::BaseInstruction
string hexToString (int)
string intToString (int)
string intToSignedString (int)
string createStringWithCPRef (string name, uint16_t index)
string tabs (int)
Detailed Description
Definition at line 9 of file _load.hpp.
Constructor & Destructor Documentation
AbstractLoad()
AbstractLoad::AbstractLoad (Attribute::CodeAttribute * code_attr, uint8_t opcode, uint8_t _load_opcode, uint8_t _loadn_base_opcode)
Definition at line 4 of file _load.cpp.
   :BaseInstruction(code_attr, opcode){
   this->is_n_class = !(opcode == _load_opcode);
   if(! this->is_n_class )
     this->code_attr->class_file->file_reader->readBytes(1, this->param);
   else
     this->param = this->opcode - _loadn_base_opcode;
 }
References AttributeInfo::class_file, ClassFile::file_reader, is_n_class, param, and FileReader::readBytes().
Member Function Documentation
execute()
int AbstractLoad::execute (Frame * frame) virtual
Reimplemented from Instructions::BaseInstruction.
Definition at line 22 of file _load.cpp.
{
   pair<uint64_t, JVMType> value = frame->local_variables.get(this->param);
   if(value.second == Byte){
     value.first = (int8_t)value.first;
   }
   if(value.second == Short){
     value.first = (int16_t)value.first;
   }
   frame->operand_stack.push(value.first, value.second);
   if(this->is_n_class)
     frame->local_pc += 1;
   else frame->local_pc += 2;
   return frame->local_pc;
 }
References Byte, LocalVariable::get(), is_n_class, Frame::local_pc, Frame::local_variables, Frame::operand_stack, param, OperandStack::push(), and Short.
getName()
virtual string Instructions::AbstractLoad::getName () pure virtual
Implemented in Instructions::Aload, Instructions::Dload, Instructions::Fload, Instructions::Lload, and Instructions::Iload.
Referenced by toString().
getType()
virtual JVMType Instructions::AbstractLoad::getType () pure virtual
Implemented in Instructions::Aload, Instructions::Dload, Instructions::Fload, Instructions::Lload, and Instructions::Iload.
toString()
string AbstractLoad::toString () virtual
Reimplemented from Instructions::BaseInstruction.
Definition at line 15 of file _load.cpp.
{
   if(this->is_n_class)
     return this->getName() + "_" + this->hexToString(this->param);
   else
     return this->getName() + " " + this->hexToString(this->param);
 }
References getName(), Instructions::BaseInstruction::hexToString(), is_n_class, and param.
Field Documentation
is_n_class
bool Instructions::AbstractLoad::is_n_class protected
Definition at line 11 of file _load.hpp.
Referenced by AbstractLoad(), execute(), and toString().
param
uint8_t Instructions::AbstractLoad::param protected
Definition at line 12 of file _load.hpp.
Referenced by AbstractLoad(), execute(), and toString().
The documentation for this class was generated from the following files:
include/attribute_info_classes/instruction_classes/_load.hpp
src/attribute_info_classes/instruction_classes/_load.cpp